create table products (
	product_id INT,
	product_name VARCHAR(50)
);
insert into products (product_id, product_name) values (1, 'Caramel Apple Chips');
insert into products (product_id, product_name) values (2, 'Bamboo Memory Foam Pillow');
insert into products (product_id, product_name) values (3, 'Buffalo Style Cauliflower Bites');
insert into products (product_id, product_name) values (4, 'Thai Coconut Curry Sauce');
insert into products (product_id, product_name) values (5, 'Adjustable Height Standing Desk Converter');
insert into products (product_id, product_name) values (6, 'Cold Brew Coffee Concentrate');
insert into products (product_id, product_name) values (7, 'Savory Pumpkin Soup');
insert into products (product_id, product_name) values (8, 'Travel Size Toiletry Bottles');
insert into products (product_id, product_name) values (9, 'Smart Home Hub');
insert into products (product_id, product_name) values (10, 'Wall Decals for Kids');
insert into products (product_id, product_name) values (11, 'Savory Italian Herbs');
insert into products (product_id, product_name) values (12, 'Grilled Vegetable Medley');
insert into products (product_id, product_name) values (13, 'Peach Slices in Syrup');
insert into products (product_id, product_name) values (14, 'Stuffed Peppers with Quinoa');
insert into products (product_id, product_name) values (15, 'Granola Bars');
insert into products (product_id, product_name) values (16, 'LED Canopy Lights');
insert into products (product_id, product_name) values (17, 'Shower Curtain Hooks');
insert into products (product_id, product_name) values (18, 'Organic Whole Wheat Flour');
insert into products (product_id, product_name) values (19, 'Coconut Cream Pie');
insert into products (product_id, product_name) values (20, 'Safety First Aid Kit');
insert into products (product_id, product_name) values (21, 'Pet Travel Bed');
insert into products (product_id, product_name) values (22, 'Thai Green Curry Paste');
insert into products (product_id, product_name) values (23, 'Hummus');
insert into products (product_id, product_name) values (24, 'Craft Beer Mustard');
insert into products (product_id, product_name) values (25, 'Travel Organizer');
insert into products (product_id, product_name) values (26, 'Californian Raisins');
insert into products (product_id, product_name) values (27, 'Casual Cropped Sweater');
insert into products (product_id, product_name) values (28, 'Sourdough Bread');
insert into products (product_id, product_name) values (29, 'Green Tea Matcha Powder');
insert into products (product_id, product_name) values (30, 'Almond Joy Bars');
insert into products (product_id, product_name) values (31, 'Hiking Boots');
insert into products (product_id, product_name) values (32, 'Tahini');
insert into products (product_id, product_name) values (33, 'Sun Protection Clothing');
insert into products (product_id, product_name) values (34, 'Sliced Bell Peppers');
insert into products (product_id, product_name) values (35, 'Wireless Charging Pad');
insert into products (product_id, product_name) values (36, 'Stainless Steel Travel Mug');
insert into products (product_id, product_name) values (37, 'Peanut Butter');
insert into products (product_id, product_name) values (38, 'Matcha Green Tea Powder');
insert into products (product_id, product_name) values (39, 'Vegetable Lentil Soup');
insert into products (product_id, product_name) values (40, 'Children''s Art Set');
insert into products (product_id, product_name) values (41, 'Chili Powder');
insert into products (product_id, product_name) values (42, 'Adjustable Kitchen Broom Stand');
insert into products (product_id, product_name) values (43, 'High-Speed Hand Blender');
insert into products (product_id, product_name) values (44, 'Camping Tent');
insert into products (product_id, product_name) values (45, 'Miso Dressing');
insert into products (product_id, product_name) values (46, 'Tabletop Fire Pit');
insert into products (product_id, product_name) values (47, 'Fruit and Nut Energy Bites');
insert into products (product_id, product_name) values (48, 'Cabbage Slaw Mix');
insert into products (product_id, product_name) values (49, 'Reusable Coffee Filter');
insert into products (product_id, product_name) values (50, 'Cranberry Orange Oatmeal');
insert into products (product_id, product_name) values (51, 'Organic Vanilla Bean Ice Cream');
insert into products (product_id, product_name) values (52, 'LED Strip Light Kit');
insert into products (product_id, product_name) values (53, 'Foam Roller for Muscle Recovery');
insert into products (product_id, product_name) values (54, 'Honey Roasted Peanuts');
insert into products (product_id, product_name) values (55, 'Banana Chips');
insert into products (product_id, product_name) values (56, 'Home Karaoke System');
insert into products (product_id, product_name) values (57, 'Chicken Parmesan Dinner Kit');
insert into products (product_id, product_name) values (58, 'Herbal Tea Variety Pack');
insert into products (product_id, product_name) values (59, 'Heat-Resistant Silicone Mat');
insert into products (product_id, product_name) values (60, 'Honey Sesame Chicken');
insert into products (product_id, product_name) values (61, 'Garden Vegetable Chips');
insert into products (product_id, product_name) values (62, 'Cream Cheese');
insert into products (product_id, product_name) values (63, 'Cucumber');
insert into products (product_id, product_name) values (64, 'Banana Nut Oatmeal Cups');
insert into products (product_id, product_name) values (65, 'Pocket Blanket');
insert into products (product_id, product_name) values (66, 'Bamboo Cutting Board');
insert into products (product_id, product_name) values (67, 'Kids'' Science Experiment Kit');
insert into products (product_id, product_name) values (68, 'Denim Jacket');
insert into products (product_id, product_name) values (69, 'Paint By Numbers Kit');
insert into products (product_id, product_name) values (70, 'Instant Read Meat Thermometer');
insert into products (product_id, product_name) values (71, 'Vegetable Broth');
insert into products (product_id, product_name) values (72, 'Spicy Hummus');
insert into products (product_id, product_name) values (73, 'Laundry Detergent');
insert into products (product_id, product_name) values (74, 'Cookbook');
insert into products (product_id, product_name) values (75, 'Nail Polish Set');
insert into products (product_id, product_name) values (76, 'Essential White Button-Up');
insert into products (product_id, product_name) values (77, 'Adjustable Garden Rake');
insert into products (product_id, product_name) values (78, 'Noise-Canceling Earbuds');
insert into products (product_id, product_name) values (79, 'Smart Water Bottle with Hydration Reminder');
insert into products (product_id, product_name) values (80, 'Coffee Capsule Dispenser');
insert into products (product_id, product_name) values (81, 'Eco-Friendly Cleaning Cloths');
insert into products (product_id, product_name) values (82, 'Mushrooms');
insert into products (product_id, product_name) values (83, 'Bock Beer Mustard');
insert into products (product_id, product_name) values (84, 'Collapsible Folding Chair');
insert into products (product_id, product_name) values (85, 'Fitness Tracker Watch');
insert into products (product_id, product_name) values (86, 'Chicken Breasts');
insert into products (product_id, product_name) values (87, 'Floral Wrap Top');
insert into products (product_id, product_name) values (88, 'Digital Drawing Tablet');
insert into products (product_id, product_name) values (89, 'Warm Knit Beanie');
insert into products (product_id, product_name) values (90, 'Relaxed Fit Henley Shirt');
insert into products (product_id, product_name) values (91, 'Children''s Musical Instrument Set');
insert into products (product_id, product_name) values (92, 'Ground Turkey');
insert into products (product_id, product_name) values (93, 'Coconut Granola');
insert into products (product_id, product_name) values (94, '3D Night Light');
insert into products (product_id, product_name) values (95, 'Chocolate Chip Cookie Mix');
insert into products (product_id, product_name) values (96, 'Coconut Cream Pie Mix');
insert into products (product_id, product_name) values (97, 'Garlic Butter Shrimp');
insert into products (product_id, product_name) values (98, 'Ethical Wool Scarf');
insert into products (product_id, product_name) values (99, 'Apple Cinnamon Breakfast Muffins');
insert into products (product_id, product_name) values (100, 'Cold Brew Coffee Concentrate');
insert into products (product_id, product_name) values (101, 'Bamboo Memory Foam Pillow');
insert into products (product_id, product_name) values (102, 'Non-Stick Baking Sheet');
insert into products (product_id, product_name) values (103, 'Pet Nail Clipper');
insert into products (product_id, product_name) values (104, 'Hot Dog Buns');
insert into products (product_id, product_name) values (105, 'Chocolate Mint Thins');
insert into products (product_id, product_name) values (106, 'Portable Blender');
insert into products (product_id, product_name) values (107, 'Glass Water Bottle');
insert into products (product_id, product_name) values (108, 'Kids'' Learning Tablet');
insert into products (product_id, product_name) values (109, 'Artisan Pickles');
insert into products (product_id, product_name) values (110, 'Adjustable Laptop Desk');
insert into products (product_id, product_name) values (111, 'Sesame Garlic Noodles');
insert into products (product_id, product_name) values (112, 'Personalized Cutting Board');
insert into products (product_id, product_name) values (113, 'Dried Apricots');
insert into products (product_id, product_name) values (114, 'Handheld Shower Head');
insert into products (product_id, product_name) values (115, 'Maple Pecan Granola');
insert into products (product_id, product_name) values (116, 'Smart Thermostat with Wi-Fi');
insert into products (product_id, product_name) values (117, 'Chipotle Black Bean Burger');
insert into products (product_id, product_name) values (118, 'Phone Case');
insert into products (product_id, product_name) values (119, 'Almond Butter Cookies');
insert into products (product_id, product_name) values (120, 'Baby Safety Corner Guards');
insert into products (product_id, product_name) values (121, 'Garlic Herb Grilled Chicken');
insert into products (product_id, product_name) values (122, 'Peanut Butter Banana Smoothie Mix');
insert into products (product_id, product_name) values (123, 'Kids'' Art Easel');
insert into products (product_id, product_name) values (124, 'Coconut Water');
insert into products (product_id, product_name) values (125, 'Dish Rack');
insert into products (product_id, product_name) values (126, 'Foldable Electric Scooter');
insert into products (product_id, product_name) values (127, 'Scent Diffuser');
insert into products (product_id, product_name) values (128, 'Interchangeable Watch Bands');
insert into products (product_id, product_name) values (129, 'Smart Light Bulbs');
insert into products (product_id, product_name) values (130, 'Cereal Dispenser with Portion Control');
insert into products (product_id, product_name) values (131, 'Fried Rice');
insert into products (product_id, product_name) values (132, 'Chic Jumpsuit');
insert into products (product_id, product_name) values (133, 'Digital Thermostat');
insert into products (product_id, product_name) values (134, 'Beef Stroganoff Meal Kit');
insert into products (product_id, product_name) values (135, 'Digital Meat Thermometer');
insert into products (product_id, product_name) values (136, 'Compact Shoe Rack');
insert into products (product_id, product_name) values (137, 'Ice Cream');
insert into products (product_id, product_name) values (138, 'Mediterranean Couscous Salad');
insert into products (product_id, product_name) values (139, 'Spinach and Feta Wraps');
insert into products (product_id, product_name) values (140, 'Chocolate Coconut Protein Balls');
insert into products (product_id, product_name) values (141, 'Self-Watering Planter');
insert into products (product_id, product_name) values (142, 'Caramel Apple Chips');
insert into products (product_id, product_name) values (143, 'Chicken Breasts');
insert into products (product_id, product_name) values (144, 'Vegetable Chips');
insert into products (product_id, product_name) values (145, 'Waffle Maker');
insert into products (product_id, product_name) values (146, 'BBQ Jackfruit');
insert into products (product_id, product_name) values (147, 'Organic Quinoa');
insert into products (product_id, product_name) values (148, 'Almond Butter Crunch Bar');
insert into products (product_id, product_name) values (149, 'Wall Art Stickers');
insert into products (product_id, product_name) values (150, 'Rainbow Veggie Chips');
insert into products (product_id, product_name) values (151, 'Pasta Portion Control Measure');
insert into products (product_id, product_name) values (152, 'Almond Butter');
insert into products (product_id, product_name) values (153, 'Roasted Garlic Mashed Potatoes');
insert into products (product_id, product_name) values (154, 'Snack Container Set');
insert into products (product_id, product_name) values (155, 'Outdoor Inflatable Pool');
insert into products (product_id, product_name) values (156, 'Kids'' Art Supplies Kit');
insert into products (product_id, product_name) values (157, 'Window Bird Feeder with Suction Cups');
insert into products (product_id, product_name) values (158, 'Ice Cream Maker');
insert into products (product_id, product_name) values (159, 'Foot Spa Bath Massager');
insert into products (product_id, product_name) values (160, 'Kids'' Craft Supplies Set');
insert into products (product_id, product_name) values (161, 'Coconut Almond Granola');
insert into products (product_id, product_name) values (162, 'Puzzle');
insert into products (product_id, product_name) values (163, 'Pet Camera with Treat Dispenser');
insert into products (product_id, product_name) values (164, 'Crispy Potato Tots');
insert into products (product_id, product_name) values (165, 'Fitness Jump Rope with LCD Counter');
insert into products (product_id, product_name) values (166, 'Classic Baseball Cap');
insert into products (product_id, product_name) values (167, 'Waffle Maker');
insert into products (product_id, product_name) values (168, 'Screen Cleaning Kit');
insert into products (product_id, product_name) values (169, 'Mediterranean Olives');
insert into products (product_id, product_name) values (170, 'Pasta Primavera');
insert into products (product_id, product_name) values (171, 'Chocolate Raspberry Tart');
insert into products (product_id, product_name) values (172, 'Scented Soy Candles');
insert into products (product_id, product_name) values (173, 'Adjustable Yoga Mat Strap');
insert into products (product_id, product_name) values (174, 'Portable Bluetooth Keyboard');
insert into products (product_id, product_name) values (175, 'Air Fryer Oven');
insert into products (product_id, product_name) values (176, 'Home Brewing Starter Kit');
insert into products (product_id, product_name) values (177, 'Kale Salad with Lemon Dressing');
insert into products (product_id, product_name) values (178, 'Diced Tomatoes (canned)');
insert into products (product_id, product_name) values (179, 'Whole Wheat Bread');
insert into products (product_id, product_name) values (180, 'Compact Refrigerator');
insert into products (product_id, product_name) values (181, 'Artisan Flatbreads');
insert into products (product_id, product_name) values (182, 'Italian Pasta');
insert into products (product_id, product_name) values (183, 'Kettle Chip Variety Pack');
insert into products (product_id, product_name) values (184, 'Canvas Wall Art');
insert into products (product_id, product_name) values (185, 'Warm Wool Sweater');
insert into products (product_id, product_name) values (186, 'Bamboo Cutting Board');
insert into products (product_id, product_name) values (187, 'Rechargeable Electric Toothbrush');
insert into products (product_id, product_name) values (188, 'Pet Tracking Collar');
insert into products (product_id, product_name) values (189, 'Lentil Soup (canned)');
insert into products (product_id, product_name) values (190, 'Folding Pocket Knife');
insert into products (product_id, product_name) values (191, 'Wall Art');
insert into products (product_id, product_name) values (192, 'Telescope');
insert into products (product_id, product_name) values (193, 'Leek and Potato Soup');
insert into products (product_id, product_name) values (194, 'Heated Throw Blanket');
insert into products (product_id, product_name) values (195, 'Chilli Lime Corn on the Cob');
insert into products (product_id, product_name) values (196, 'LED Strip Lights Kit');
insert into products (product_id, product_name) values (197, 'Cranberry Citrus Sauce');
insert into products (product_id, product_name) values (198, 'Sliced Olives');
insert into products (product_id, product_name) values (199, 'Organic Italian Seasoning');
insert into products (product_id, product_name) values (200, 'Tortilla Chips');
insert into products (product_id, product_name) values (201, 'Raspberry Vanilla Greek Yogurt');
insert into products (product_id, product_name) values (202, 'Classic Black Dress');
insert into products (product_id, product_name) values (203, 'Oven-Baked Chicken Tenders');
insert into products (product_id, product_name) values (204, 'Cinnamon Roll Protein Bar');
insert into products (product_id, product_name) values (205, 'Smartphone Hand Grip');
insert into products (product_id, product_name) values (206, 'Pasta Maker');
insert into products (product_id, product_name) values (207, 'LED Table Lamp');
insert into products (product_id, product_name) values (208, 'Lemon Herb Grilled Chicken');
insert into products (product_id, product_name) values (209, 'Wall Calendar');
insert into products (product_id, product_name) values (210, 'Sturdy Bookends');
insert into products (product_id, product_name) values (211, 'Outdoor Portable Fire Pit');
insert into products (product_id, product_name) values (212, 'Wireless Wi-Fi Extender');
insert into products (product_id, product_name) values (213, 'Oven Mitts with Pocket');
insert into products (product_id, product_name) values (214, 'Organic Honeycrisp Apples');
insert into products (product_id, product_name) values (215, 'Fitness Mat');
insert into products (product_id, product_name) values (216, 'Wireless Charging Pad');
insert into products (product_id, product_name) values (217, 'Silicone Baking Mat');
insert into products (product_id, product_name) values (218, 'Comfy Slippers');
insert into products (product_id, product_name) values (219, 'Dark Chocolate Raisins');
insert into products (product_id, product_name) values (220, 'Kitchen Scale');
insert into products (product_id, product_name) values (221, 'Portable Phone Mug Holder');
insert into products (product_id, product_name) values (222, 'Silicone Stretch Lids');
insert into products (product_id, product_name) values (223, 'Garlic Herb Cream Cheese');
insert into products (product_id, product_name) values (224, 'Sesame Garlic Noodles');
insert into products (product_id, product_name) values (225, 'Personal Blender with Travel Cup');
insert into products (product_id, product_name) values (226, 'Jasmine Rice');
insert into products (product_id, product_name) values (227, 'Creative Puzzle Game');
insert into products (product_id, product_name) values (228, 'LED Strip Lights Kit');
insert into products (product_id, product_name) values (229, 'Ethical Wool Scarf');
insert into products (product_id, product_name) values (230, 'Toilet Paper (12 rolls)');
insert into products (product_id, product_name) values (231, 'Avocado Oil');
insert into products (product_id, product_name) values (232, 'Homestyle Chicken Noodle Soup');
insert into products (product_id, product_name) values (233, 'Safety Goggles');
insert into products (product_id, product_name) values (234, 'Oven-Baked Potato Chips');
insert into products (product_id, product_name) values (235, 'Electric Rice Cooker with Steamer');
insert into products (product_id, product_name) values (236, 'Car Diagnostic Scanner');
insert into products (product_id, product_name) values (237, 'Garlic Naan Bread');
insert into products (product_id, product_name) values (238, 'Coconut Chips');
insert into products (product_id, product_name) values (239, 'Sliced Turkey Breast');
insert into products (product_id, product_name) values (240, 'Traditional Hummus');
insert into products (product_id, product_name) values (241, 'Herbal Garden Starter Kit');
insert into products (product_id, product_name) values (242, 'Coconut Cream');
insert into products (product_id, product_name) values (243, 'Smart Water Bottle');
insert into products (product_id, product_name) values (244, 'Electric Food Slicer');
insert into products (product_id, product_name) values (245, 'Air Mattress');
insert into products (product_id, product_name) values (246, 'Wireless HDMI Receiver');
insert into products (product_id, product_name) values (247, 'Casual Cropped Sweater');
insert into products (product_id, product_name) values (248, 'Fitness Smartwatch');
insert into products (product_id, product_name) values (249, 'Homestyle Chicken Noodle Soup');
insert into products (product_id, product_name) values (250, 'Chopping Board');
insert into products (product_id, product_name) values (251, 'Shower Curtain Hooks');
insert into products (product_id, product_name) values (252, 'Sweet Potatoes');
insert into products (product_id, product_name) values (253, 'Tomato Basil Pasta Sauce');
insert into products (product_id, product_name) values (254, 'Nutritional Yeast');
insert into products (product_id, product_name) values (255, 'Mixed Nuts');
insert into products (product_id, product_name) values (256, 'Peanut Butter Pretzel Nuggets');
insert into products (product_id, product_name) values (257, 'Portable Leaf Blower');
insert into products (product_id, product_name) values (258, 'Wall-Mounted Bookshelf');
insert into products (product_id, product_name) values (259, 'Quinoa');
insert into products (product_id, product_name) values (260, 'Coconut Almond Granola');
insert into products (product_id, product_name) values (261, 'Grapes (red)');
insert into products (product_id, product_name) values (262, 'Self-Cleaning Water Bottle');
insert into products (product_id, product_name) values (263, 'Portable Camping Stove');
insert into products (product_id, product_name) values (264, 'Chocolate Mint Thins');
insert into products (product_id, product_name) values (265, 'Voice-Controlled Speaker');
insert into products (product_id, product_name) values (266, 'Chocolate Chip Cookie Mix');
insert into products (product_id, product_name) values (267, 'Cork Yoga Mat');
insert into products (product_id, product_name) values (268, 'Overnight Hiking Backpack');
insert into products (product_id, product_name) values (269, 'Field Journal');
insert into products (product_id, product_name) values (270, 'Portable Speakers');
insert into products (product_id, product_name) values (271, 'Fruit and Nut Bars');
insert into products (product_id, product_name) values (272, 'Blackberry Jam');
insert into products (product_id, product_name) values (273, 'Sea Salt Caramel Brownie');
insert into products (product_id, product_name) values (274, 'Portable Air Compressor');
insert into products (product_id, product_name) values (275, 'Sweetened Condensed Milk');
insert into products (product_id, product_name) values (276, 'Pumpkin Spice Muffins');
insert into products (product_id, product_name) values (277, 'Peas (frozen)');
insert into products (product_id, product_name) values (278, 'Kale & Quinoa Salad Mix');
insert into products (product_id, product_name) values (279, 'Pesto Pasta Sauce');
insert into products (product_id, product_name) values (280, 'Recipe Book Stand');
insert into products (product_id, product_name) values (281, 'Gluten-Free Pancake Mix');
insert into products (product_id, product_name) values (282, 'Cabbage');
insert into products (product_id, product_name) values (283, 'Garlic Parmesan Roasted Potatoes');
insert into products (product_id, product_name) values (284, 'Honey Garlic Shrimp');
insert into products (product_id, product_name) values (285, 'Handmade Leather Journal');
insert into products (product_id, product_name) values (286, 'Biodegradable Dog Waste Bags');
insert into products (product_id, product_name) values (287, 'LED Disco Ball Light');
insert into products (product_id, product_name) values (288, 'Herb Garden Planter Box');
insert into products (product_id, product_name) values (289, 'Dried Mango Slices');
insert into products (product_id, product_name) values (290, 'Home Karaoke System');
insert into products (product_id, product_name) values (291, 'Peach & Mango Salsa');
insert into products (product_id, product_name) values (292, 'Fresh Lemons');
insert into products (product_id, product_name) values (293, 'Smartphone Photography Tripod');
insert into products (product_id, product_name) values (294, 'Pet Carrier Backpack');
insert into products (product_id, product_name) values (295, 'Handheld Garment Steamer');
insert into products (product_id, product_name) values (296, 'Applewood Smoked Bacon');
insert into products (product_id, product_name) values (297, 'Fruit and Nut Energy Bites');
insert into products (product_id, product_name) values (298, 'Puzzle 3D Model Kit');
insert into products (product_id, product_name) values (299, 'Cotton Sweatpants');
insert into products (product_id, product_name) values (300, 'Mobile Workbench');
insert into products (product_id, product_name) values (301, 'Mango Salsa');
insert into products (product_id, product_name) values (302, 'Brussels Sprouts');
insert into products (product_id, product_name) values (303, 'Electric Opener for Jars and Bottles');
insert into products (product_id, product_name) values (304, 'Patterned Knit Scarf');
insert into products (product_id, product_name) values (305, 'Chickpea Flour');
insert into products (product_id, product_name) values (306, 'Pet Food Storage Container');
insert into products (product_id, product_name) values (307, 'Teriyaki Chicken Stir-Fry');
insert into products (product_id, product_name) values (308, 'Wall-Mounted Bookshelf');
insert into products (product_id, product_name) values (309, 'Rolling Cooler');
insert into products (product_id, product_name) values (310, 'Adjustable Window Blind');
insert into products (product_id, product_name) values (311, 'Digital Drawing Tablet');
insert into products (product_id, product_name) values (312, 'DIY Organic Gardening Kit');
insert into products (product_id, product_name) values (313, 'Honey Roasted Chickpeas');
insert into products (product_id, product_name) values (314, 'Chili Lime Shrimp');
insert into products (product_id, product_name) values (315, 'Electronic Drum Kit');
insert into products (product_id, product_name) values (316, 'Spicy Vegetable Sushi Rolls');
insert into products (product_id, product_name) values (317, 'Sour Cream');
insert into products (product_id, product_name) values (318, 'Travel Luggage Scale');
insert into products (product_id, product_name) values (319, 'Reusable Produce Bags Set');
insert into products (product_id, product_name) values (320, 'Floral Summer Dress');
insert into products (product_id, product_name) values (321, 'Mayonnaise');
insert into products (product_id, product_name) values (322, 'LED Makeup Mirror');
insert into products (product_id, product_name) values (323, 'Basil Pesto Pasta');
insert into products (product_id, product_name) values (324, 'Rain Jacket');
insert into products (product_id, product_name) values (325, 'Blue Denim Jeans');
insert into products (product_id, product_name) values (326, 'Portable Massage Gun');
insert into products (product_id, product_name) values (327, 'Spinach and Feta Stuffed Chicken Breast');
insert into products (product_id, product_name) values (328, 'Mediterranean Chickpea Bowl');
insert into products (product_id, product_name) values (329, 'Low-Fat Cottage Cheese');
insert into products (product_id, product_name) values (330, 'Roasted Garlic Mashed Potatoes');
insert into products (product_id, product_name) values (331, 'Chickpeas');
insert into products (product_id, product_name) values (332, 'Silicone Baking Mat Set');
insert into products (product_id, product_name) values (333, 'Luxury Bathrobe');
insert into products (product_id, product_name) values (334, 'Pumpkin Pancake Mix');
insert into products (product_id, product_name) values (335, 'Brown Rice');
insert into products (product_id, product_name) values (336, 'Pressure Cooker');
insert into products (product_id, product_name) values (337, 'Electric Heating Pad');
insert into products (product_id, product_name) values (338, 'Fettuccine Alfredo Dinner Kit');
insert into products (product_id, product_name) values (339, 'Dog Training Collar');
insert into products (product_id, product_name) values (340, 'Almond Joy Bars');
insert into products (product_id, product_name) values (341, 'Over-The-Door Shoe Organizer');
insert into products (product_id, product_name) values (342, 'Portable USB-C Monitor');
insert into products (product_id, product_name) values (343, 'Sesame Noodles');
insert into products (product_id, product_name) values (344, 'Thai Peanut Noodles');
insert into products (product_id, product_name) values (345, 'Spicy Snack Mix');
insert into products (product_id, product_name) values (346, 'Grass Fed Beef Patties');
insert into products (product_id, product_name) values (347, 'Smart Fitness Scale');
insert into products (product_id, product_name) values (348, 'Electric Blanket');
insert into products (product_id, product_name) values (349, 'Luxury Bath Salts');
insert into products (product_id, product_name) values (350, 'Organic Apples');
insert into products (product_id, product_name) values (351, 'Luxury Rolling Makeup Case');
insert into products (product_id, product_name) values (352, 'Smoked Paprika');
insert into products (product_id, product_name) values (353, 'Pet Carrier Backpack');
insert into products (product_id, product_name) values (354, 'Vegetable Stir-Fry Kit');
insert into products (product_id, product_name) values (355, 'Pet Grooming Glove');
insert into products (product_id, product_name) values (356, 'LED Desk Light');
insert into products (product_id, product_name) values (357, 'Tomato Paste');
insert into products (product_id, product_name) values (358, 'Vegetable Chips');
insert into products (product_id, product_name) values (359, 'Ground Cinnamon');
insert into products (product_id, product_name) values (360, 'Portable Solar Path Lights');
insert into products (product_id, product_name) values (361, 'Portable Bluetooth Headphones');
insert into products (product_id, product_name) values (362, 'Chocolate Chip Pancake Mix');
insert into products (product_id, product_name) values (363, 'Wireless Music Receiver');
insert into products (product_id, product_name) values (364, 'Jump Rope with Counter');
insert into products (product_id, product_name) values (365, 'Glass Tea Pot');
insert into products (product_id, product_name) values (366, 'Non-Toxic Concrete Sealer');
insert into products (product_id, product_name) values (367, 'Chia Seeds');
insert into products (product_id, product_name) values (368, 'Chewy Granola Bars');
insert into products (product_id, product_name) values (369, 'Chocolate Hazelnut Spread');
insert into products (product_id, product_name) values (370, 'Pine Nuts');
insert into products (product_id, product_name) values (371, 'Soft Plush Throw Blanket');
insert into products (product_id, product_name) values (372, 'Colorful Post-It Notes Set');
insert into products (product_id, product_name) values (373, 'Magnetic Puzzle Board');
insert into products (product_id, product_name) values (374, 'Tennis Racket');
insert into products (product_id, product_name) values (375, 'Maple Breakfast Sausage');
insert into products (product_id, product_name) values (376, 'Vegetable Stir Fry Mix');
insert into products (product_id, product_name) values (377, 'USB Flash Drive');
insert into products (product_id, product_name) values (378, 'Set of Silicone Cooking Utensils');
insert into products (product_id, product_name) values (379, 'Customizable Name Plate');
insert into products (product_id, product_name) values (380, 'Digital Meat Thermometer');
insert into products (product_id, product_name) values (381, 'Chunky Knit Sweater');
insert into products (product_id, product_name) values (382, 'Elderberry Syrup');
insert into products (product_id, product_name) values (383, 'Vegetable Chips');
insert into products (product_id, product_name) values (384, 'Sweet Potato & Kale Hash');
insert into products (product_id, product_name) values (385, 'Chocolate Avocado Pudding');
insert into products (product_id, product_name) values (386, 'Vegan Mayonnaise');
insert into products (product_id, product_name) values (387, 'Memory Foam Mattress Pad');
insert into products (product_id, product_name) values (388, 'Garlic Herb Cream Cheese');
insert into products (product_id, product_name) values (389, 'Outdoor String Lights');
insert into products (product_id, product_name) values (390, 'Fashionable Fanny Pack');
insert into products (product_id, product_name) values (391, 'Screen Cleaning Kit');
insert into products (product_id, product_name) values (392, 'Ready-to-Eat Chili');
insert into products (product_id, product_name) values (393, 'Frozen Berry Blend');
insert into products (product_id, product_name) values (394, 'Savory Quinoa Pudding');
insert into products (product_id, product_name) values (395, 'Granulated Sugar');
insert into products (product_id, product_name) values (396, 'Sun Protection Clothing');
insert into products (product_id, product_name) values (397, 'Electric Milk Frother');
insert into products (product_id, product_name) values (398, 'Sustainable Wooden Toys');
insert into products (product_id, product_name) values (399, 'Self-Massaging Pillow');
insert into products (product_id, product_name) values (400, 'Pineapple Coconut Yogurt');
insert into products (product_id, product_name) values (401, 'Wireless Music Receiver');
insert into products (product_id, product_name) values (402, 'Coconut Oil');
insert into products (product_id, product_name) values (403, 'Organic Coconut Flour');
insert into products (product_id, product_name) values (404, 'Chino Shorts');
insert into products (product_id, product_name) values (405, 'Portable Leaf Blower');
insert into products (product_id, product_name) values (406, 'Maple Glazed Carrots');
insert into products (product_id, product_name) values (407, 'Sun Protection Clothing');
insert into products (product_id, product_name) values (408, 'Plant Watering Spikes');
insert into products (product_id, product_name) values (409, 'Baby Monitor');
insert into products (product_id, product_name) values (410, 'Sesame Noodles');
insert into products (product_id, product_name) values (411, 'Granola');
insert into products (product_id, product_name) values (412, 'Sports Windbreaker');
insert into products (product_id, product_name) values (413, 'Adjustable Pet Grooming Table');
insert into products (product_id, product_name) values (414, 'Portable Air Purifier');
insert into products (product_id, product_name) values (415, 'Graphic Print Leggings');
insert into products (product_id, product_name) values (416, 'Laptop Sleeve');
insert into products (product_id, product_name) values (417, 'Inflatable Pool Float');
insert into products (product_id, product_name) values (418, 'Peach Mango Smoothie');
insert into products (product_id, product_name) values (419, 'Fridge Magnet Set');
insert into products (product_id, product_name) values (420, 'Whisk Set');
insert into products (product_id, product_name) values (421, 'Apple Cinnamon Breakfast Muffins');
insert into products (product_id, product_name) values (422, 'Red Lentils');
insert into products (product_id, product_name) values (423, 'Stainless Steel Grater');
insert into products (product_id, product_name) values (424, 'Portable Campfire');
insert into products (product_id, product_name) values (425, 'Pet Camera with Treat Dispenser');
insert into products (product_id, product_name) values (426, 'Gaming Headset');
insert into products (product_id, product_name) values (427, 'Noise-Canceling Earbuds');
insert into products (product_id, product_name) values (428, 'Frozen Edamame');
insert into products (product_id, product_name) values (429, 'Hydration Backpack');
insert into products (product_id, product_name) values (430, 'Himalayan Pink Salt');
insert into products (product_id, product_name) values (431, 'Lemon Basil Pasta Sauce');
insert into products (product_id, product_name) values (432, 'Maple Cinnamon Granola Bars');
insert into products (product_id, product_name) values (433, 'Apple Cinnamon Oatmeal');
insert into products (product_id, product_name) values (434, 'Screen Cleaning Kit');
insert into products (product_id, product_name) values (435, 'Pressure Cooker');
insert into products (product_id, product_name) values (436, 'Wireless Charging Station');
insert into products (product_id, product_name) values (437, 'Almond Joy Snack Bars');
insert into products (product_id, product_name) values (438, 'Incense Holder');
insert into products (product_id, product_name) values (439, 'Vegan Tacos');
insert into products (product_id, product_name) values (440, 'Outdoor Inflatable Pool');
insert into products (product_id, product_name) values (441, 'Mini Hand Gesture Drone');
insert into products (product_id, product_name) values (442, 'Puffed Rice Cake');
insert into products (product_id, product_name) values (443, 'Wooden Puzzle Game');
insert into products (product_id, product_name) values (444, 'Portable Blender');
insert into products (product_id, product_name) values (445, 'Foam Muscle Roller');
insert into products (product_id, product_name) values (446, 'Kids'' Gardening Kit');
insert into products (product_id, product_name) values (447, 'Puzzle Game Set');
insert into products (product_id, product_name) values (448, 'Cream Cheese');
insert into products (product_id, product_name) values (449, 'Silicone Baking Molds');
insert into products (product_id, product_name) values (450, 'Oven-Baked Potato Chips');
insert into products (product_id, product_name) values (451, 'Green Tea Matcha Powder');
insert into products (product_id, product_name) values (452, 'Chickpea Salad');
insert into products (product_id, product_name) values (453, 'Adjustable Stand for Tablets and Smartphones');
insert into products (product_id, product_name) values (454, 'Adjustable Standing Desk');
insert into products (product_id, product_name) values (455, 'Maple Almond Granola');
insert into products (product_id, product_name) values (456, 'Pear and Gorgonzola Salad');
insert into products (product_id, product_name) values (457, 'Brownie Bites');
insert into products (product_id, product_name) values (458, 'Ultra-Thin Laptop Sleeve');
insert into products (product_id, product_name) values (459, 'Feta Cheese');
insert into products (product_id, product_name) values (460, 'Ginger Turmeric Shots');
insert into products (product_id, product_name) values (461, 'Sweet Potato and Chickpea Bowl');
insert into products (product_id, product_name) values (462, 'Wall-Mounted Wine Rack');
insert into products (product_id, product_name) values (463, 'Pasta Sauce Mix');
insert into products (product_id, product_name) values (464, 'Roasted Chickpeas');
insert into products (product_id, product_name) values (465, 'Bluetooth Car Adapter');
insert into products (product_id, product_name) values (466, 'Bluetooth Headphones');
insert into products (product_id, product_name) values (467, 'Electric Nail File Kit');
insert into products (product_id, product_name) values (468, 'Plant-Based Protein Bars');
insert into products (product_id, product_name) values (469, 'Kitchen Scale');
insert into products (product_id, product_name) values (470, 'Creamy Ranch Dressing');
insert into products (product_id, product_name) values (471, 'Fettuccine Alfredo Dinner Kit');
insert into products (product_id, product_name) values (472, 'Chickpeas');
insert into products (product_id, product_name) values (473, 'Lentil Soup');
insert into products (product_id, product_name) values (474, 'Multi-Functional Rice Cooker');
insert into products (product_id, product_name) values (475, 'Kettle Corn Popcorn');
insert into products (product_id, product_name) values (476, 'Savory Snack Mix');
insert into products (product_id, product_name) values (477, 'Cranberry Almond Granola');
insert into products (product_id, product_name) values (478, 'Eco-Friendly Disposable Plates');
insert into products (product_id, product_name) values (479, 'Printed Maxi Skirt');
insert into products (product_id, product_name) values (480, 'Fridge Magnet Set');
insert into products (product_id, product_name) values (481, 'Savory Italian Herbs');
insert into products (product_id, product_name) values (482, 'Ground Turkey');
insert into products (product_id, product_name) values (483, 'Travel Pillow');
insert into products (product_id, product_name) values (484, 'Customizable Name Plate');
insert into products (product_id, product_name) values (485, 'Fruit and Nut Medley');
insert into products (product_id, product_name) values (486, 'Vegetable Pizza Rolls');
insert into products (product_id, product_name) values (487, 'Portable Grill Cover');
insert into products (product_id, product_name) values (488, 'Scented Candle Set');
insert into products (product_id, product_name) values (489, 'Aged White Cheddar Popcorn');
insert into products (product_id, product_name) values (490, 'Portable Projector');
insert into products (product_id, product_name) values (491, 'Ready-to-Eat Chili');
insert into products (product_id, product_name) values (492, 'Collapsible Folding Chair');
insert into products (product_id, product_name) values (493, 'Silicone Baking Mat');
insert into products (product_id, product_name) values (494, 'Classic Black Trousers');
insert into products (product_id, product_name) values (495, 'Orange Ginger Vinaigrette');
insert into products (product_id, product_name) values (496, 'Denim Jacket');
insert into products (product_id, product_name) values (497, 'Linen Trousers');
insert into products (product_id, product_name) values (498, 'Drone');
insert into products (product_id, product_name) values (499, 'Crispy Potato Tots');
insert into products (product_id, product_name) values (500, 'Vegetable Sushi Rolls');
insert into products (product_id, product_name) values (501, 'Rainbow Veggie Chips');
insert into products (product_id, product_name) values (502, 'Classic Bagels');
insert into products (product_id, product_name) values (503, 'Cocktail Shaker Set');
insert into products (product_id, product_name) values (504, 'Ultraviolet Phone Sanitizer');
insert into products (product_id, product_name) values (505, 'Garlic Herb Grilled Chicken');
insert into products (product_id, product_name) values (506, 'Portable Bluetooth Speaker');
insert into products (product_id, product_name) values (507, 'Shoe Organizer');
insert into products (product_id, product_name) values (508, 'Organic Blueberries');
insert into products (product_id, product_name) values (509, 'Chocolate Almond Milk');
insert into products (product_id, product_name) values (510, 'Almond Flour Brownies');
insert into products (product_id, product_name) values (511, 'Acoustic Guitar');
insert into products (product_id, product_name) values (512, 'Maple Almond Granola');
insert into products (product_id, product_name) values (513, 'Granola Bars');
insert into products (product_id, product_name) values (514, 'Vegan Alfredo Sauce');
insert into products (product_id, product_name) values (515, 'Compost Bin');
insert into products (product_id, product_name) values (516, 'Granola Bars');
insert into products (product_id, product_name) values (517, 'Dried Apricots');
insert into products (product_id, product_name) values (518, 'Fitness Mat');
insert into products (product_id, product_name) values (519, 'Savory Mushroom Risotto');
insert into products (product_id, product_name) values (520, 'French Bread');
insert into products (product_id, product_name) values (521, 'Classic Caesar Dressing');
insert into products (product_id, product_name) values (522, 'Luxury Bath Robe');
insert into products (product_id, product_name) values (523, 'Organic Coconut Oil');
insert into products (product_id, product_name) values (524, 'Pet Training Pads');
insert into products (product_id, product_name) values (525, 'Vegan Mayonnaise');
insert into products (product_id, product_name) values (526, 'Samsung Galaxy Smartwatch');
insert into products (product_id, product_name) values (527, 'Garlic Parmesan Roasted Nuts');
insert into products (product_id, product_name) values (528, 'Sliced Avocado');
insert into products (product_id, product_name) values (529, 'Spiced Pumpkin Soup');
insert into products (product_id, product_name) values (530, 'Chili Garlic Sauce');
insert into products (product_id, product_name) values (531, 'Almond Butter Cups');
insert into products (product_id, product_name) values (532, 'Digital Bullet Journal');
insert into products (product_id, product_name) values (533, 'Artisan Cornbread Mix');
insert into products (product_id, product_name) values (534, 'Eggs (dozen)');
insert into products (product_id, product_name) values (535, 'Classic Caesar Dressing');
insert into products (product_id, product_name) values (536, 'Pet Camera with Treat Dispenser');
insert into products (product_id, product_name) values (537, 'Kettle BBQ Grill');
insert into products (product_id, product_name) values (538, 'Avocado Oil');
insert into products (product_id, product_name) values (539, 'Spicy Tuna Sushi Kit');
insert into products (product_id, product_name) values (540, 'Sweet Chili Dipping Sauce');
insert into products (product_id, product_name) values (541, 'Wine Glasses');
insert into products (product_id, product_name) values (542, 'Wrap Jumpsuit');
insert into products (product_id, product_name) values (543, 'Balsamic Vinaigrette');
insert into products (product_id, product_name) values (544, 'Caramelized Onion Dip');
insert into products (product_id, product_name) values (545, 'Dog Training Whistle');
insert into products (product_id, product_name) values (546, 'Classic Caesar Salad Kit');
insert into products (product_id, product_name) values (547, 'Garlic and Herb Cream Cheese');
insert into products (product_id, product_name) values (548, 'Electric Rice Cooker');
insert into products (product_id, product_name) values (549, 'Golf Putting Green');
insert into products (product_id, product_name) values (550, 'Winter Knit Beanie');
insert into products (product_id, product_name) values (551, 'Linen Trousers');
insert into products (product_id, product_name) values (552, 'Rustic Italian Breads');
insert into products (product_id, product_name) values (553, 'Over-The-Door Shoe Organizer');
insert into products (product_id, product_name) values (554, 'Rechargeable Electric Toothbrush');
insert into products (product_id, product_name) values (555, 'Bicycle Lock');
insert into products (product_id, product_name) values (556, 'Classic Cheeseburger Mix');
insert into products (product_id, product_name) values (557, 'Gardening Gloves');
insert into products (product_id, product_name) values (558, 'Berries Medley');
insert into products (product_id, product_name) values (559, 'Marinara Sauce');
insert into products (product_id, product_name) values (560, 'Honey Nut Cheerios');
insert into products (product_id, product_name) values (561, 'Over-The-Door Shoe Organizer');
insert into products (product_id, product_name) values (562, 'Organic Brown Sugar');
insert into products (product_id, product_name) values (563, 'Teriyaki Chicken Wings');
insert into products (product_id, product_name) values (564, 'Frozen Cauliflower Rice');
insert into products (product_id, product_name) values (565, 'High-Speed Hand Blender');
insert into products (product_id, product_name) values (566, 'Portable Hammock');
insert into products (product_id, product_name) values (567, 'Pistachio Ice Cream');
insert into products (product_id, product_name) values (568, 'Garden Hose');
insert into products (product_id, product_name) values (569, 'Microfiber Cleaning Cloth Set');
insert into products (product_id, product_name) values (570, 'Smart Thermostat');
insert into products (product_id, product_name) values (571, 'Paint By Numbers Kit');
insert into products (product_id, product_name) values (572, 'Digital Kitchen Timer');
insert into products (product_id, product_name) values (573, 'Children''s Backpack');
insert into products (product_id, product_name) values (574, 'Black Bean Soup');
insert into products (product_id, product_name) values (575, 'Vegetable Korma');
insert into products (product_id, product_name) values (576, 'Maple Cinnamon Granola');
insert into products (product_id, product_name) values (577, 'Yoga Strap');
insert into products (product_id, product_name) values (578, 'Beach Cover-Up');
insert into products (product_id, product_name) values (579, 'Personal Blender with Travel Cup');
insert into products (product_id, product_name) values (580, 'Glass Tea Pot');
insert into products (product_id, product_name) values (581, 'Collapsible Colander');
insert into products (product_id, product_name) values (582, 'Children''s Educational Workbook');
insert into products (product_id, product_name) values (583, 'Cable Knit Beanie');
insert into products (product_id, product_name) values (584, 'Garden Kneeler and Seat');
insert into products (product_id, product_name) values (585, 'Coconut Milk Yogurt');
insert into products (product_id, product_name) values (586, 'Plant-Based Meal Prep Containers');
insert into products (product_id, product_name) values (587, 'Chili Beans (canned)');
insert into products (product_id, product_name) values (588, 'Garlic Breadsticks');
insert into products (product_id, product_name) values (589, 'Almond Butter Granola Bars');
insert into products (product_id, product_name) values (590, 'Portable Campfire');
insert into products (product_id, product_name) values (591, 'Smart WiFi Plug');
insert into products (product_id, product_name) values (592, 'Smart Home Security Camera');
insert into products (product_id, product_name) values (593, 'Shredded Cheese');
insert into products (product_id, product_name) values (594, 'Dog Walking Waist Pack');
insert into products (product_id, product_name) values (595, 'Board Game');
insert into products (product_id, product_name) values (596, 'Aged White Cheddar Popcorn');
insert into products (product_id, product_name) values (597, 'Pet Waterer with Filtration');
insert into products (product_id, product_name) values (598, 'Digital Kitchen Timer');
insert into products (product_id, product_name) values (599, 'Smart Plant Monitor');
insert into products (product_id, product_name) values (600, 'Portable Projector');
insert into products (product_id, product_name) values (601, 'Tailored Blazer');
insert into products (product_id, product_name) values (602, 'Watering Can with Nozzle');
insert into products (product_id, product_name) values (603, 'Fresh Basil Pesto');
insert into products (product_id, product_name) values (604, 'Wrap Jumpsuit');
insert into products (product_id, product_name) values (605, 'Diced Tomatoes (canned)');
insert into products (product_id, product_name) values (606, 'Pet Carrier Backpack');
insert into products (product_id, product_name) values (607, 'Indian Curry Sauce');
insert into products (product_id, product_name) values (608, 'Orange Ginger Vinaigrette');
insert into products (product_id, product_name) values (609, 'Mango Chunks');
insert into products (product_id, product_name) values (610, 'Fitbit Activity Tracker');
insert into products (product_id, product_name) values (611, 'Dog Car Seat Cover');
insert into products (product_id, product_name) values (612, 'Digital Bullet Journal');
insert into products (product_id, product_name) values (613, 'Ice Cube Tray with Lid');
insert into products (product_id, product_name) values (614, 'Sriracha Hot Chili Sauce');
insert into products (product_id, product_name) values (615, 'Digital Food Scale');
insert into products (product_id, product_name) values (616, 'Yoga Mat Carrier');
insert into products (product_id, product_name) values (617, 'Greek Yogurt Parfait');
insert into products (product_id, product_name) values (618, 'Honey Lemon Tea');
insert into products (product_id, product_name) values (619, 'Leather Crossbody Bag');
insert into products (product_id, product_name) values (620, 'Suede Ankle Booties');
insert into products (product_id, product_name) values (621, 'Maple Pecan Granola');
insert into products (product_id, product_name) values (622, 'Plant Growing Kit');
insert into products (product_id, product_name) values (623, 'Peach Slices (canned)');
insert into products (product_id, product_name) values (624, 'Savory Snack Mix');
insert into products (product_id, product_name) values (625, 'Voice-Controlled Speaker');
insert into products (product_id, product_name) values (626, 'Pumpkin Waffles');
insert into products (product_id, product_name) values (627, 'Zesty Cilantro Lime Dressing');
insert into products (product_id, product_name) values (628, 'Peas (frozen)');
insert into products (product_id, product_name) values (629, 'Savory Rice Cakes');
insert into products (product_id, product_name) values (630, 'Vegetarian Sausage Links');
insert into products (product_id, product_name) values (631, 'Memory Foam Mattress Topper');
insert into products (product_id, product_name) values (632, 'Crispy Onion Rings');
insert into products (product_id, product_name) values (633, 'Pepperoni Pizza Roll-Ups');
insert into products (product_id, product_name) values (634, 'Creamy Garlic Mashed Potatoes');
insert into products (product_id, product_name) values (635, 'Honey Butter Popcorn');
insert into products (product_id, product_name) values (636, 'Tortilla Chips');
insert into products (product_id, product_name) values (637, 'Honey Lemon Tea');
insert into products (product_id, product_name) values (638, 'Car Seat Organizer');
insert into products (product_id, product_name) values (639, 'Hummus');
insert into products (product_id, product_name) values (640, 'Adjustable Dumbbells');
insert into products (product_id, product_name) values (641, 'Smart Home Hub');
insert into products (product_id, product_name) values (642, 'Electric Fondue Pot');
insert into products (product_id, product_name) values (643, 'Frozen Burritos');
insert into products (product_id, product_name) values (644, 'Mesh Laundry Bags Set');
insert into products (product_id, product_name) values (645, 'Golf Putting Green');
insert into products (product_id, product_name) values (646, 'Golf Polo Shirt');
insert into products (product_id, product_name) values (647, 'Tandoori Chicken Skewers');
insert into products (product_id, product_name) values (648, 'Faux Fur Coat');
insert into products (product_id, product_name) values (649, 'Cheesy Cauliflower Bake');
insert into products (product_id, product_name) values (650, 'Adjustable Garden Rake');
insert into products (product_id, product_name) values (651, 'Plant-Based Protein Bars');
insert into products (product_id, product_name) values (652, 'Pork Chops');
insert into products (product_id, product_name) values (653, 'Basmati Rice');
insert into products (product_id, product_name) values (654, 'Sweet and Sour Sauce');
insert into products (product_id, product_name) values (655, 'Rechargeable Electric Toothbrush');
insert into products (product_id, product_name) values (656, 'Rustic Italian Breads');
insert into products (product_id, product_name) values (657, 'Pizza Stone');
insert into products (product_id, product_name) values (658, 'Comfortable Bed Pillow');
insert into products (product_id, product_name) values (659, 'Spinach Feta Wraps');
insert into products (product_id, product_name) values (660, 'Margherita Pizza');
insert into products (product_id, product_name) values (661, 'Sliced Bell Peppers');
insert into products (product_id, product_name) values (662, 'Chocolate Almond Milk');
insert into products (product_id, product_name) values (663, 'Oats');
insert into products (product_id, product_name) values (664, 'Vegetable Quinoa Bowl');
insert into products (product_id, product_name) values (665, 'Chicken Parmesan Dinner Kit');
insert into products (product_id, product_name) values (666, 'Electric Food Steamer');
insert into products (product_id, product_name) values (667, 'Honey Roasted Almonds');
insert into products (product_id, product_name) values (668, 'Adjustable Dumbbells');
insert into products (product_id, product_name) values (669, 'Compact Dishwasher');
insert into products (product_id, product_name) values (670, 'Pumpkin Pie Spice');
insert into products (product_id, product_name) values (671, 'Wooden Blocks');
insert into products (product_id, product_name) values (672, 'Classic Slim Fit Shirt');
insert into products (product_id, product_name) values (673, 'Italian Herb Balsamic Marinade');
insert into products (product_id, product_name) values (674, 'Electronic Drum Kit');
insert into products (product_id, product_name) values (675, 'Compressible Packing Cubes');
insert into products (product_id, product_name) values (676, 'Red Lentil Pasta');
insert into products (product_id, product_name) values (677, 'Basic V-Neck T-Shirt');
insert into products (product_id, product_name) values (678, 'Foldable Picnic Table');
insert into products (product_id, product_name) values (679, 'Athletic Compression Tights');
insert into products (product_id, product_name) values (680, 'Baking Soda');
insert into products (product_id, product_name) values (681, 'DIY Candle Making Kit');
insert into products (product_id, product_name) values (682, 'Bamboo Cotton Tank Top');
insert into products (product_id, product_name) values (683, 'Pet Grooming Scissors');
insert into products (product_id, product_name) values (684, 'Homestyle Beef Stew');
insert into products (product_id, product_name) values (685, 'Sun-Dried Tomatoes');
insert into products (product_id, product_name) values (686, 'Oats');
insert into products (product_id, product_name) values (687, 'Reflective Safety Vest');
insert into products (product_id, product_name) values (688, 'Fitness Jump Rope with LCD Counter');
insert into products (product_id, product_name) values (689, 'Cherry Almond Protein Bar');
insert into products (product_id, product_name) values (690, 'Heat-Resistant Silicone Mat');
insert into products (product_id, product_name) values (691, 'Roasted Garlic Butter');
insert into products (product_id, product_name) values (692, 'Veggie Lovers Pizza');
insert into products (product_id, product_name) values (693, 'Chipotle Black Bean Burger');
insert into products (product_id, product_name) values (694, 'Laptop Backpack');
insert into products (product_id, product_name) values (695, 'Savory Oatmeal');
insert into products (product_id, product_name) values (696, 'Portable Bluetooth Headphones');
insert into products (product_id, product_name) values (697, 'Natural Fruit Snacks');
insert into products (product_id, product_name) values (698, 'Rustic Italian Breads');
insert into products (product_id, product_name) values (699, 'Teriyaki Salmon Fillets');
insert into products (product_id, product_name) values (700, 'Pet Bed');
insert into products (product_id, product_name) values (701, 'Chocolate Syrup');
insert into products (product_id, product_name) values (702, 'Ice Pack');
insert into products (product_id, product_name) values (703, 'Mesh Sports Leggings');
insert into products (product_id, product_name) values (704, 'Honey Roasted Chickpeas');
insert into products (product_id, product_name) values (705, 'Wireless Induction Charger');
insert into products (product_id, product_name) values (706, 'Chunky Knit Sweater');
insert into products (product_id, product_name) values (707, 'Honeycrisp Apple Chips');
insert into products (product_id, product_name) values (708, 'Tomatillo Salsa');
insert into products (product_id, product_name) values (709, 'Tomatillo Salsa');
insert into products (product_id, product_name) values (710, 'Maple Bacon Popcorn');
insert into products (product_id, product_name) values (711, 'Savory Pumpkin Soup');
insert into products (product_id, product_name) values (712, 'Creamy Garlic Dressing');
insert into products (product_id, product_name) values (713, 'Foam Muscle Roller');
insert into products (product_id, product_name) values (714, 'Travel Shoe Bags Set');
insert into products (product_id, product_name) values (715, 'Chilli Lime Corn on the Cob');
insert into products (product_id, product_name) values (716, 'Organic Black Rice');
insert into products (product_id, product_name) values (717, 'Frozen Spinach');
insert into products (product_id, product_name) values (718, 'Art Supplies Organizer');
insert into products (product_id, product_name) values (719, 'Pretzel Bites');
insert into products (product_id, product_name) values (720, 'Peach Slices (canned)');
insert into products (product_id, product_name) values (721, 'Almond Flour Tortillas');
insert into products (product_id, product_name) values (722, 'Avocado Lime Dressing');
insert into products (product_id, product_name) values (723, 'Rechargeable Laptop Battery Pack');
insert into products (product_id, product_name) values (724, 'Pineapple Coconut Rice Mix');
insert into products (product_id, product_name) values (725, 'Rustic Italian Bread');
insert into products (product_id, product_name) values (726, 'Terry Cloth Robe');
insert into products (product_id, product_name) values (727, 'Homestyle Chicken Noodle Soup');
insert into products (product_id, product_name) values (728, 'Whole Wheat Pita Bread');
insert into products (product_id, product_name) values (729, 'Mushroom Soup (canned)');
insert into products (product_id, product_name) values (730, 'Pet Nail Clipper');
insert into products (product_id, product_name) values (731, 'Silicone Wine Glasses');
insert into products (product_id, product_name) values (732, 'Hummus Variety Pack');
insert into products (product_id, product_name) values (733, 'Sturdy Bookends');
insert into products (product_id, product_name) values (734, 'Maple Bacon Potato Chips');
insert into products (product_id, product_name) values (735, 'Ultraviolet Phone Sanitizer');
insert into products (product_id, product_name) values (736, 'Window Bird Feeder');
insert into products (product_id, product_name) values (737, 'Hair Dryer');
insert into products (product_id, product_name) values (738, 'Magnetic Whiteboard');
insert into products (product_id, product_name) values (739, 'Andouille Sausage');
insert into products (product_id, product_name) values (740, 'Car Windshield Sun Shade');
insert into products (product_id, product_name) values (741, 'Chicken Parmesan Dinner Kit');
insert into products (product_id, product_name) values (742, 'Salsa');
insert into products (product_id, product_name) values (743, 'Kale Salad Kit');
insert into products (product_id, product_name) values (744, 'Cordless Water Flosser');
insert into products (product_id, product_name) values (745, 'Foldable Picnic Table');
insert into products (product_id, product_name) values (746, 'Travel Jewelry Organizer');
insert into products (product_id, product_name) values (747, 'Creative Puzzle Game');
insert into products (product_id, product_name) values (748, 'Personalized Cutting Board');
insert into products (product_id, product_name) values (749, 'Survival Gear Kit');
insert into products (product_id, product_name) values (750, 'Frozen Acai Bowl');
insert into products (product_id, product_name) values (751, 'Sweetened Condensed Milk');
insert into products (product_id, product_name) values (752, 'Scented Soy Candles');
insert into products (product_id, product_name) values (753, 'Peach Salsa');
insert into products (product_id, product_name) values (754, 'Raisin Cinnamon Granola');
insert into products (product_id, product_name) values (755, 'Hand Mixer');
insert into products (product_id, product_name) values (756, 'Smoky BBQ Jackfruit');
insert into products (product_id, product_name) values (757, 'Organic Tomato Soup');
insert into products (product_id, product_name) values (758, 'Chocolate Raspberry Tart');
insert into products (product_id, product_name) values (759, 'Collapsible Water Bottle');
insert into products (product_id, product_name) values (760, 'Leather Biker Jacket');
insert into products (product_id, product_name) values (761, 'Adjustable Resistance Bands');
insert into products (product_id, product_name) values (762, 'Smart WiFi Plug');
insert into products (product_id, product_name) values (763, 'Cucumber');
insert into products (product_id, product_name) values (764, 'Wireless Music Receiver');
insert into products (product_id, product_name) values (765, 'Crispy Kale Chips');
insert into products (product_id, product_name) values (766, 'Athletic Compression Tights');
insert into products (product_id, product_name) values (767, 'Butternut Squash Soup');
insert into products (product_id, product_name) values (768, 'Mobile Workbench');
insert into products (product_id, product_name) values (769, 'Fettuccine Alfredo Dinner Kit');
insert into products (product_id, product_name) values (770, 'Raspberry Lemonade Mix');
insert into products (product_id, product_name) values (771, 'Incense Holder');
insert into products (product_id, product_name) values (772, 'Scent Diffuser');
insert into products (product_id, product_name) values (773, 'Organic Vanilla Bean Ice Cream');
insert into products (product_id, product_name) values (774, 'USB Flash Drive');
insert into products (product_id, product_name) values (775, 'Almond Butter Cookies');
insert into products (product_id, product_name) values (776, 'Wireless Range Extender');
insert into products (product_id, product_name) values (777, 'Frozen Spinach');
insert into products (product_id, product_name) values (778, 'Laptop Stand');
insert into products (product_id, product_name) values (779, 'Wireless Music Receiver');
insert into products (product_id, product_name) values (780, 'Travel Eye Mask with Ear Plugs');
insert into products (product_id, product_name) values (781, 'Vegetable Pizza Rolls');
insert into products (product_id, product_name) values (782, 'Dark Chocolate Covered Pretzels');
insert into products (product_id, product_name) values (783, 'Laundry Detergent');
insert into products (product_id, product_name) values (784, 'Spaghetti and Meatball Dinner Kit');
insert into products (product_id, product_name) values (785, 'Almond Butter Cookies');
insert into products (product_id, product_name) values (786, 'Organic Almonds');
insert into products (product_id, product_name) values (787, 'Non-Toxic Crayons for Kids');
insert into products (product_id, product_name) values (788, 'Kettle Chip Variety Pack');
insert into products (product_id, product_name) values (789, 'Electric Heat Press Machine');
insert into products (product_id, product_name) values (790, 'Blueberry Oatmeal Cups');
insert into products (product_id, product_name) values (791, 'Smartwatch');
insert into products (product_id, product_name) values (792, 'Smart Scale');
insert into products (product_id, product_name) values (793, 'Cream Cheese');
insert into products (product_id, product_name) values (794, 'Pet Travel Backpack Carrier');
insert into products (product_id, product_name) values (795, 'Kids'' Art Easel');
insert into products (product_id, product_name) values (796, 'Garden Tool Belt');
insert into products (product_id, product_name) values (797, 'Teriyaki Chicken Skewers');
insert into products (product_id, product_name) values (798, 'Gaming Mousepad');
insert into products (product_id, product_name) values (799, 'Handcrafted Wooden Jewelry Box');
insert into products (product_id, product_name) values (800, 'Home Brewing Starter Kit');
insert into products (product_id, product_name) values (801, 'Watercolor Set');
insert into products (product_id, product_name) values (802, 'Linen Trousers');
insert into products (product_id, product_name) values (803, 'Garden Vegetable Chips');
insert into products (product_id, product_name) values (804, 'Athletic Sports Bra');
insert into products (product_id, product_name) values (805, 'Travel Laundry Bag');
insert into products (product_id, product_name) values (806, 'Ergonomic Gaming Chair');
insert into products (product_id, product_name) values (807, 'Floral Summer Dress');
insert into products (product_id, product_name) values (808, 'Fitness Tracker Band');
insert into products (product_id, product_name) values (809, 'Savory Breakfast Sausage');
insert into products (product_id, product_name) values (810, 'Poppy Seed Dressing');
insert into products (product_id, product_name) values (811, 'Mini Food Processor');
insert into products (product_id, product_name) values (812, 'Banana Nut Muffins');
insert into products (product_id, product_name) values (813, 'Bock Beer Mustard');
insert into products (product_id, product_name) values (814, 'Snack Container Set');
insert into products (product_id, product_name) values (815, 'DIY Organic Gardening Kit');
insert into products (product_id, product_name) values (816, 'Nutritional Yeast');
insert into products (product_id, product_name) values (817, 'Organic Almond Flour');
insert into products (product_id, product_name) values (818, 'Wireless Earbud Silicone Covers');
insert into products (product_id, product_name) values (819, 'Drone');
insert into products (product_id, product_name) values (820, 'Dark Chocolate Raisins');
insert into products (product_id, product_name) values (821, 'Cinnamon Sugar Popcorn');
insert into products (product_id, product_name) values (822, 'Frozen Chicken Nuggets');
insert into products (product_id, product_name) values (823, 'Rain Jacket');
insert into products (product_id, product_name) values (824, 'Vegetable Potstickers');
insert into products (product_id, product_name) values (825, 'Pesto Pasta Salad');
insert into products (product_id, product_name) values (826, 'Portable Solar Generator');
insert into products (product_id, product_name) values (827, 'Rechargeable Battery Organizer');
insert into products (product_id, product_name) values (828, 'Vegetable Pizza Rolls');
insert into products (product_id, product_name) values (829, 'LED Desk Lamp with USB Charging Port');
insert into products (product_id, product_name) values (830, 'Slim Fit Chinos');
insert into products (product_id, product_name) values (831, 'Mini Projector for Smartphones');
insert into products (product_id, product_name) values (832, 'Jalapeño Cornbread');
insert into products (product_id, product_name) values (833, 'Beach Cover-Up');
insert into products (product_id, product_name) values (834, 'Over-the-Door Hooks');
insert into products (product_id, product_name) values (835, 'Organic Lentil Soup');
insert into products (product_id, product_name) values (836, 'Caraway Rye Bread');
insert into products (product_id, product_name) values (837, 'Electric Ice Cream Maker');
insert into products (product_id, product_name) values (838, 'Chino Shorts');
insert into products (product_id, product_name) values (839, 'Shower Curtain Hooks');
insert into products (product_id, product_name) values (840, 'Sea Salt Tortilla Chips');
insert into products (product_id, product_name) values (841, 'Multi-Purpose Marine Rope');
insert into products (product_id, product_name) values (842, 'Educational STEM Kit');
insert into products (product_id, product_name) values (843, 'Electric Egg Cooker');
insert into products (product_id, product_name) values (844, 'Chili Lime Corn Chips');
insert into products (product_id, product_name) values (845, 'Reusable Silicone Food Storage Bags');
insert into products (product_id, product_name) values (846, 'Golf Putting Green');
insert into products (product_id, product_name) values (847, 'Pecan Nuts');
insert into products (product_id, product_name) values (848, 'Vanilla Pudding Mix');
insert into products (product_id, product_name) values (849, 'Eggs (dozen)');
insert into products (product_id, product_name) values (850, 'Rechargeable Battery Organizer');
insert into products (product_id, product_name) values (851, 'Salt and Pepper Grinder Set');
insert into products (product_id, product_name) values (852, 'Smart Light Bulbs');
insert into products (product_id, product_name) values (853, 'Zesty Cilantro Lime Dressing');
insert into products (product_id, product_name) values (854, 'Camera Lens Cleaning Kit');
insert into products (product_id, product_name) values (855, 'Mushrooms');
insert into products (product_id, product_name) values (856, 'Vegetable Stock');
insert into products (product_id, product_name) values (857, 'Pineapple Chunks (canned)');
insert into products (product_id, product_name) values (858, 'Flavored Popcorn Mix');
insert into products (product_id, product_name) values (859, 'Wall Decals for Kids');
insert into products (product_id, product_name) values (860, 'Chilli Lime Corn on the Cob');
insert into products (product_id, product_name) values (861, 'Magic Color-Changing Mug');
insert into products (product_id, product_name) values (862, 'Mini Electric Kettle');
insert into products (product_id, product_name) values (863, 'Motion Sensor Light');
insert into products (product_id, product_name) values (864, 'Poppy Seed Dressing');
insert into products (product_id, product_name) values (865, 'Coconut Bowls Set');
insert into products (product_id, product_name) values (866, 'Portable USB-C Monitor');
insert into products (product_id, product_name) values (867, 'Bicycle Repair Kit');
insert into products (product_id, product_name) values (868, 'Tuscan Bean Soup');
insert into products (product_id, product_name) values (869, 'Backpack');
insert into products (product_id, product_name) values (870, 'Roasted Garlic Pasta Sauce');
insert into products (product_id, product_name) values (871, 'Mini Cordless Vacuum Cleaner');
insert into products (product_id, product_name) values (872, 'Chocolate Almond Milk');
insert into products (product_id, product_name) values (873, 'Casual Cropped Sweater');
insert into products (product_id, product_name) values (874, 'Running Shorts');
insert into products (product_id, product_name) values (875, 'Ethical Wool Scarf');
insert into products (product_id, product_name) values (876, 'Spicy Roasted Nuts');
insert into products (product_id, product_name) values (877, 'Cordless Water Flosser');
insert into products (product_id, product_name) values (878, 'Chickpea Flour');
insert into products (product_id, product_name) values (879, 'Chicken Breasts');
insert into products (product_id, product_name) values (880, 'Adjustable Skipping Rope');
insert into products (product_id, product_name) values (881, 'Blue Denim Jeans');
insert into products (product_id, product_name) values (882, 'Salt and Pepper Grinder Set');
insert into products (product_id, product_name) values (883, 'Coconut Yogurt');
insert into products (product_id, product_name) values (884, 'Honey Ginger Tea');
insert into products (product_id, product_name) values (885, 'Tropical Fruit Bowl');
insert into products (product_id, product_name) values (886, 'Honey Sriracha Chicken Bites');
insert into products (product_id, product_name) values (887, 'Floral Wrap Top');
insert into products (product_id, product_name) values (888, 'Aged White Cheddar Popcorn');
insert into products (product_id, product_name) values (889, 'Inflatable Paddle Board');
insert into products (product_id, product_name) values (890, 'Screen Cleaning Kit');
insert into products (product_id, product_name) values (891, 'Chiffon Blouse');
insert into products (product_id, product_name) values (892, 'Interactive Plush Toy');
insert into products (product_id, product_name) values (893, 'Solar String Lights');
insert into products (product_id, product_name) values (894, 'Pesto Pasta Sauce');
insert into products (product_id, product_name) values (895, 'Stainless Steel Cutlery Set');
insert into products (product_id, product_name) values (896, 'Kids'' Trampoline');
insert into products (product_id, product_name) values (897, 'Sous Vide Cooker');
insert into products (product_id, product_name) values (898, 'Truffle Parmesan Fries');
insert into products (product_id, product_name) values (899, 'Rice Cakes');
insert into products (product_id, product_name) values (900, 'Mediterranean Chickpea Bowl');
insert into products (product_id, product_name) values (901, 'Outdoor Adventure Kit');
insert into products (product_id, product_name) values (902, 'Electric Nail File Kit');
insert into products (product_id, product_name) values (903, 'Organic Cereal Bars');
insert into products (product_id, product_name) values (904, 'Classic Cheeseburger Mix');
insert into products (product_id, product_name) values (905, 'Balsamic Vinegar');
insert into products (product_id, product_name) values (906, 'Travel Luggage Scale');
insert into products (product_id, product_name) values (907, 'Herbed Chicken Breast');
insert into products (product_id, product_name) values (908, 'Almond Flour');
insert into products (product_id, product_name) values (909, 'Brussels Sprouts');
insert into products (product_id, product_name) values (910, 'Zucchini Noodles');
insert into products (product_id, product_name) values (911, 'Memory Foam Mattress Topper');
insert into products (product_id, product_name) values (912, 'Wooden Toy Train Set');
insert into products (product_id, product_name) values (913, 'Scent Diffuser Oil');
insert into products (product_id, product_name) values (914, 'Garlic Herb Cream Cheese');
insert into products (product_id, product_name) values (915, 'Memory Foam Mattress Topper');
insert into products (product_id, product_name) values (916, 'Electric Griddle with Lid');
insert into products (product_id, product_name) values (917, 'Plant Growing Kit');
insert into products (product_id, product_name) values (918, 'Blueberry Muffin Mix');
insert into products (product_id, product_name) values (919, 'Elderberry Syrup Kit');
insert into products (product_id, product_name) values (920, 'Greek Yogurt Parfait');
insert into products (product_id, product_name) values (921, 'Decorative LED Neon Sign');
insert into products (product_id, product_name) values (922, 'Air Fryer');
insert into products (product_id, product_name) values (923, 'Noise Reduction Headphones');
insert into products (product_id, product_name) values (924, 'Peach Fruit Cups');
insert into products (product_id, product_name) values (925, 'Vegetable Medley');
insert into products (product_id, product_name) values (926, 'Crispy Onion Rings');
insert into products (product_id, product_name) values (927, 'Sweet Pea Hummus');
insert into products (product_id, product_name) values (928, 'Spicy Chicken Wings');
insert into products (product_id, product_name) values (929, 'Peanut Butter Banana Smoothie');
insert into products (product_id, product_name) values (930, 'Water Bottle with Built-in Fruit Infuser');
insert into products (product_id, product_name) values (931, 'Herbal Garden Starter Kit');
insert into products (product_id, product_name) values (932, 'Black Bean & Corn Salad');
insert into products (product_id, product_name) values (933, 'Traditional Hummus');
insert into products (product_id, product_name) values (934, 'Compressible Packing Cubes');
insert into products (product_id, product_name) values (935, 'Biodegradable Dog Waste Bags');
insert into products (product_id, product_name) values (936, 'Non-Stick Baking Sheets');
insert into products (product_id, product_name) values (937, 'Organic Brown Rice Cakes');
insert into products (product_id, product_name) values (938, 'Travel Mug with Leak-Proof Lid');
insert into products (product_id, product_name) values (939, 'Portable Campfire');
insert into products (product_id, product_name) values (940, 'Baked Mac and Cheese');
insert into products (product_id, product_name) values (941, 'Vegetable Fried Rice');
insert into products (product_id, product_name) values (942, 'Tandoori Chicken Marinade');
insert into products (product_id, product_name) values (943, 'Cauliflower Pizza Crust');
insert into products (product_id, product_name) values (944, 'Electric Meat Grinder');
insert into products (product_id, product_name) values (945, 'Canned Black Beans');
insert into products (product_id, product_name) values (946, 'Adjustable Window Blind');
insert into products (product_id, product_name) values (947, 'Maple Almond Yogurt');
insert into products (product_id, product_name) values (948, 'Wireless Charger');
insert into products (product_id, product_name) values (949, 'Men''s Waterproof Hiking Boots');
insert into products (product_id, product_name) values (950, 'Wireless Charger');
insert into products (product_id, product_name) values (951, 'High-Quality Yoga Mat');
insert into products (product_id, product_name) values (952, 'Chocolate Coconut Granola');
insert into products (product_id, product_name) values (953, 'Honey Sesame Cashews');
insert into products (product_id, product_name) values (954, 'Maple Oatmeal');
insert into products (product_id, product_name) values (955, 'Sooji (Semolina)');
insert into products (product_id, product_name) values (956, 'Snack Container Set');
insert into products (product_id, product_name) values (957, 'Sesame Garlic Stir-Fry Sauce');
insert into products (product_id, product_name) values (958, 'Mini Hand Gesture Drone');
insert into products (product_id, product_name) values (959, 'Incense Holder');
insert into products (product_id, product_name) values (960, 'Silicone Baking Mat Set');
insert into products (product_id, product_name) values (961, 'High-Quality Yoga Mat');
insert into products (product_id, product_name) values (962, 'Stylish Wide-Leg Trousers');
insert into products (product_id, product_name) values (963, 'Rice Pudding');
insert into products (product_id, product_name) values (964, 'Silicone Cooking Utensils Set');
insert into products (product_id, product_name) values (965, 'Cinnamon Sugar Mix');
insert into products (product_id, product_name) values (966, 'Pretzel Bites');
insert into products (product_id, product_name) values (967, 'Coffee Making Kit');
insert into products (product_id, product_name) values (968, 'Chocolate Chip Cookie Mix');
insert into products (product_id, product_name) values (969, 'Peanut Butter');
insert into products (product_id, product_name) values (970, 'Vegan Caesar Dressing');
insert into products (product_id, product_name) values (971, 'Sweet Potatoes (organic)');
insert into products (product_id, product_name) values (972, 'Honey Almond Granola Bars');
insert into products (product_id, product_name) values (973, 'Ripped Boyfriend Jeans');
insert into products (product_id, product_name) values (974, 'Herb Garlic Butter');
insert into products (product_id, product_name) values (975, 'Crafting Kit');
insert into products (product_id, product_name) values (976, 'Watercolor Set');
insert into products (product_id, product_name) values (977, 'Smoked Paprika');
insert into products (product_id, product_name) values (978, 'Greek Yogurt Parfait');
insert into products (product_id, product_name) values (979, 'Spicy Avocado Salsa');
insert into products (product_id, product_name) values (980, 'Dark Chocolate Raisins');
insert into products (product_id, product_name) values (981, 'Portable Solar Path Lights');
insert into products (product_id, product_name) values (982, 'Coconut Cream Pie Mix');
insert into products (product_id, product_name) values (983, 'Coconut Yogurt');
insert into products (product_id, product_name) values (984, 'Wall Decals for Kids');
insert into products (product_id, product_name) values (985, 'Spicy Thai Noodles');
insert into products (product_id, product_name) values (986, 'Bird Feeder');
insert into products (product_id, product_name) values (987, 'Almond Butter Crunch Bar');
insert into products (product_id, product_name) values (988, 'Smartphone Holder for Car');
insert into products (product_id, product_name) values (989, 'Crispy Onion Rings');
insert into products (product_id, product_name) values (990, 'Ankle Boots');
insert into products (product_id, product_name) values (991, 'Elegant Lace Dress');
insert into products (product_id, product_name) values (992, 'Insulated Wine Tote');
insert into products (product_id, product_name) values (993, 'Smartphone Gimbal Stabilizer');
insert into products (product_id, product_name) values (994, 'Water Bottle with Built-in Fruit Infuser');
insert into products (product_id, product_name) values (995, 'Hiking Gaiters');
insert into products (product_id, product_name) values (996, 'Chocolate Chip Muffins');
insert into products (product_id, product_name) values (997, 'Peas (frozen)');
insert into products (product_id, product_name) values (998, 'Vacuum Sealer Machine');
insert into products (product_id, product_name) values (999, 'Lentil Soup (canned)');
insert into products (product_id, product_name) values (1000, 'Mini Food Processor');
