create table departments (
	department_id INT,
	department_name VARCHAR(50)
);
insert into departments (department_id, department_name) values (1, 'Training');
insert into departments (department_id, department_name) values (2, 'Legal');
insert into departments (department_id, department_name) values (3, 'Engineering');
insert into departments (department_id, department_name) values (4, 'Marketing');
insert into departments (department_id, department_name) values (5, 'Business Development');
insert into departments (department_id, department_name) values (6, 'Accounting');
insert into departments (department_id, department_name) values (7, 'Accounting');
insert into departments (department_id, department_name) values (8, 'Support');
insert into departments (department_id, department_name) values (9, 'Marketing');
insert into departments (department_id, department_name) values (10, 'Training');
insert into departments (department_id, department_name) values (11, 'Research and Development');
insert into departments (department_id, department_name) values (12, 'Sales');
insert into departments (department_id, department_name) values (13, 'Engineering');
insert into departments (department_id, department_name) values (14, 'Business Development');
insert into departments (department_id, department_name) values (15, 'Legal');
insert into departments (department_id, department_name) values (16, 'Legal');
insert into departments (department_id, department_name) values (17, 'Human Resources');
insert into departments (department_id, department_name) values (18, 'Human Resources');
insert into departments (department_id, department_name) values (19, 'Human Resources');
insert into departments (department_id, department_name) values (20, 'Engineering');
insert into departments (department_id, department_name) values (21, 'Research and Development');
insert into departments (department_id, department_name) values (22, 'Services');
insert into departments (department_id, department_name) values (23, 'Services');
insert into departments (department_id, department_name) values (24, 'Human Resources');
insert into departments (department_id, department_name) values (25, 'Training');
insert into departments (department_id, department_name) values (26, 'Training');
insert into departments (department_id, department_name) values (27, 'Services');
insert into departments (department_id, department_name) values (28, 'Research and Development');
insert into departments (department_id, department_name) values (29, 'Support');
insert into departments (department_id, department_name) values (30, 'Services');
insert into departments (department_id, department_name) values (31, 'Product Management');
insert into departments (department_id, department_name) values (32, 'Human Resources');
insert into departments (department_id, department_name) values (33, 'Marketing');
insert into departments (department_id, department_name) values (34, 'Support');
insert into departments (department_id, department_name) values (35, 'Research and Development');
insert into departments (department_id, department_name) values (36, 'Sales');
insert into departments (department_id, department_name) values (37, 'Accounting');
insert into departments (department_id, department_name) values (38, 'Sales');
insert into departments (department_id, department_name) values (39, 'Training');
insert into departments (department_id, department_name) values (40, 'Accounting');
insert into departments (department_id, department_name) values (41, 'Product Management');
insert into departments (department_id, department_name) values (42, 'Support');
insert into departments (department_id, department_name) values (43, 'Research and Development');
insert into departments (department_id, department_name) values (44, 'Accounting');
insert into departments (department_id, department_name) values (45, 'Training');
insert into departments (department_id, department_name) values (46, 'Engineering');
insert into departments (department_id, department_name) values (47, 'Sales');
insert into departments (department_id, department_name) values (48, 'Engineering');
insert into departments (department_id, department_name) values (49, 'Marketing');
insert into departments (department_id, department_name) values (50, 'Research and Development');
insert into departments (department_id, department_name) values (51, 'Business Development');
insert into departments (department_id, department_name) values (52, 'Support');
insert into departments (department_id, department_name) values (53, 'Services');
insert into departments (department_id, department_name) values (54, 'Legal');
insert into departments (department_id, department_name) values (55, 'Legal');
insert into departments (department_id, department_name) values (56, 'Legal');
insert into departments (department_id, department_name) values (57, 'Marketing');
insert into departments (department_id, department_name) values (58, 'Training');
insert into departments (department_id, department_name) values (59, 'Legal');
insert into departments (department_id, department_name) values (60, 'Business Development');
insert into departments (department_id, department_name) values (61, 'Engineering');
insert into departments (department_id, department_name) values (62, 'Sales');
insert into departments (department_id, department_name) values (63, 'Business Development');
insert into departments (department_id, department_name) values (64, 'Legal');
insert into departments (department_id, department_name) values (65, 'Services');
insert into departments (department_id, department_name) values (66, 'Human Resources');
insert into departments (department_id, department_name) values (67, 'Services');
insert into departments (department_id, department_name) values (68, 'Business Development');
insert into departments (department_id, department_name) values (69, 'Training');
insert into departments (department_id, department_name) values (70, 'Training');
insert into departments (department_id, department_name) values (71, 'Human Resources');
insert into departments (department_id, department_name) values (72, 'Support');
insert into departments (department_id, department_name) values (73, 'Human Resources');
insert into departments (department_id, department_name) values (74, 'Marketing');
insert into departments (department_id, department_name) values (75, 'Support');
insert into departments (department_id, department_name) values (76, 'Sales');
insert into departments (department_id, department_name) values (77, 'Accounting');
insert into departments (department_id, department_name) values (78, 'Accounting');
insert into departments (department_id, department_name) values (79, 'Training');
insert into departments (department_id, department_name) values (80, 'Legal');
insert into departments (department_id, department_name) values (81, 'Support');
insert into departments (department_id, department_name) values (82, 'Support');
insert into departments (department_id, department_name) values (83, 'Marketing');
insert into departments (department_id, department_name) values (84, 'Engineering');
insert into departments (department_id, department_name) values (85, 'Sales');
insert into departments (department_id, department_name) values (86, 'Services');
insert into departments (department_id, department_name) values (87, 'Legal');
insert into departments (department_id, department_name) values (88, 'Engineering');
insert into departments (department_id, department_name) values (89, 'Business Development');
insert into departments (department_id, department_name) values (90, 'Sales');
insert into departments (department_id, department_name) values (91, 'Business Development');
insert into departments (department_id, department_name) values (92, 'Engineering');
insert into departments (department_id, department_name) values (93, 'Product Management');
insert into departments (department_id, department_name) values (94, 'Product Management');
insert into departments (department_id, department_name) values (95, 'Services');
insert into departments (department_id, department_name) values (96, 'Engineering');
insert into departments (department_id, department_name) values (97, 'Human Resources');
insert into departments (department_id, department_name) values (98, 'Support');
insert into departments (department_id, department_name) values (99, 'Product Management');
insert into departments (department_id, department_name) values (100, 'Business Development');
insert into departments (department_id, department_name) values (101, 'Product Management');
insert into departments (department_id, department_name) values (102, 'Sales');
insert into departments (department_id, department_name) values (103, 'Support');
insert into departments (department_id, department_name) values (104, 'Human Resources');
insert into departments (department_id, department_name) values (105, 'Legal');
insert into departments (department_id, department_name) values (106, 'Support');
insert into departments (department_id, department_name) values (107, 'Support');
insert into departments (department_id, department_name) values (108, 'Research and Development');
insert into departments (department_id, department_name) values (109, 'Research and Development');
insert into departments (department_id, department_name) values (110, 'Training');
insert into departments (department_id, department_name) values (111, 'Sales');
insert into departments (department_id, department_name) values (112, 'Research and Development');
insert into departments (department_id, department_name) values (113, 'Sales');
insert into departments (department_id, department_name) values (114, 'Engineering');
insert into departments (department_id, department_name) values (115, 'Legal');
insert into departments (department_id, department_name) values (116, 'Human Resources');
insert into departments (department_id, department_name) values (117, 'Sales');
insert into departments (department_id, department_name) values (118, 'Engineering');
insert into departments (department_id, department_name) values (119, 'Engineering');
insert into departments (department_id, department_name) values (120, 'Product Management');
insert into departments (department_id, department_name) values (121, 'Engineering');
insert into departments (department_id, department_name) values (122, 'Accounting');
insert into departments (department_id, department_name) values (123, 'Sales');
insert into departments (department_id, department_name) values (124, 'Business Development');
insert into departments (department_id, department_name) values (125, 'Research and Development');
insert into departments (department_id, department_name) values (126, 'Sales');
insert into departments (department_id, department_name) values (127, 'Services');
insert into departments (department_id, department_name) values (128, 'Product Management');
insert into departments (department_id, department_name) values (129, 'Accounting');
insert into departments (department_id, department_name) values (130, 'Sales');
insert into departments (department_id, department_name) values (131, 'Sales');
insert into departments (department_id, department_name) values (132, 'Legal');
insert into departments (department_id, department_name) values (133, 'Sales');
insert into departments (department_id, department_name) values (134, 'Services');
insert into departments (department_id, department_name) values (135, 'Sales');
insert into departments (department_id, department_name) values (136, 'Services');
insert into departments (department_id, department_name) values (137, 'Sales');
insert into departments (department_id, department_name) values (138, 'Services');
insert into departments (department_id, department_name) values (139, 'Services');
insert into departments (department_id, department_name) values (140, 'Engineering');
insert into departments (department_id, department_name) values (141, 'Support');
insert into departments (department_id, department_name) values (142, 'Research and Development');
insert into departments (department_id, department_name) values (143, 'Legal');
insert into departments (department_id, department_name) values (144, 'Accounting');
insert into departments (department_id, department_name) values (145, 'Marketing');
insert into departments (department_id, department_name) values (146, 'Sales');
insert into departments (department_id, department_name) values (147, 'Services');
insert into departments (department_id, department_name) values (148, 'Sales');
insert into departments (department_id, department_name) values (149, 'Support');
insert into departments (department_id, department_name) values (150, 'Services');
insert into departments (department_id, department_name) values (151, 'Marketing');
insert into departments (department_id, department_name) values (152, 'Product Management');
insert into departments (department_id, department_name) values (153, 'Research and Development');
insert into departments (department_id, department_name) values (154, 'Research and Development');
insert into departments (department_id, department_name) values (155, 'Engineering');
insert into departments (department_id, department_name) values (156, 'Engineering');
insert into departments (department_id, department_name) values (157, 'Product Management');
insert into departments (department_id, department_name) values (158, 'Legal');
insert into departments (department_id, department_name) values (159, 'Accounting');
insert into departments (department_id, department_name) values (160, 'Research and Development');
insert into departments (department_id, department_name) values (161, 'Sales');
insert into departments (department_id, department_name) values (162, 'Marketing');
insert into departments (department_id, department_name) values (163, 'Services');
insert into departments (department_id, department_name) values (164, 'Accounting');
insert into departments (department_id, department_name) values (165, 'Sales');
insert into departments (department_id, department_name) values (166, 'Engineering');
insert into departments (department_id, department_name) values (167, 'Legal');
insert into departments (department_id, department_name) values (168, 'Accounting');
insert into departments (department_id, department_name) values (169, 'Marketing');
insert into departments (department_id, department_name) values (170, 'Product Management');
insert into departments (department_id, department_name) values (171, 'Human Resources');
insert into departments (department_id, department_name) values (172, 'Business Development');
insert into departments (department_id, department_name) values (173, 'Training');
insert into departments (department_id, department_name) values (174, 'Services');
insert into departments (department_id, department_name) values (175, 'Training');
insert into departments (department_id, department_name) values (176, 'Marketing');
insert into departments (department_id, department_name) values (177, 'Research and Development');
insert into departments (department_id, department_name) values (178, 'Training');
insert into departments (department_id, department_name) values (179, 'Legal');
insert into departments (department_id, department_name) values (180, 'Services');
insert into departments (department_id, department_name) values (181, 'Business Development');
insert into departments (department_id, department_name) values (182, 'Human Resources');
insert into departments (department_id, department_name) values (183, 'Accounting');
insert into departments (department_id, department_name) values (184, 'Services');
insert into departments (department_id, department_name) values (185, 'Human Resources');
insert into departments (department_id, department_name) values (186, 'Product Management');
insert into departments (department_id, department_name) values (187, 'Accounting');
insert into departments (department_id, department_name) values (188, 'Training');
insert into departments (department_id, department_name) values (189, 'Training');
insert into departments (department_id, department_name) values (190, 'Services');
insert into departments (department_id, department_name) values (191, 'Sales');
insert into departments (department_id, department_name) values (192, 'Legal');
insert into departments (department_id, department_name) values (193, 'Accounting');
insert into departments (department_id, department_name) values (194, 'Engineering');
insert into departments (department_id, department_name) values (195, 'Services');
insert into departments (department_id, department_name) values (196, 'Sales');
insert into departments (department_id, department_name) values (197, 'Research and Development');
insert into departments (department_id, department_name) values (198, 'Services');
insert into departments (department_id, department_name) values (199, 'Sales');
insert into departments (department_id, department_name) values (200, 'Sales');
insert into departments (department_id, department_name) values (201, 'Business Development');
insert into departments (department_id, department_name) values (202, 'Accounting');
insert into departments (department_id, department_name) values (203, 'Product Management');
insert into departments (department_id, department_name) values (204, 'Support');
insert into departments (department_id, department_name) values (205, 'Marketing');
insert into departments (department_id, department_name) values (206, 'Business Development');
insert into departments (department_id, department_name) values (207, 'Engineering');
insert into departments (department_id, department_name) values (208, 'Marketing');
insert into departments (department_id, department_name) values (209, 'Accounting');
insert into departments (department_id, department_name) values (210, 'Sales');
insert into departments (department_id, department_name) values (211, 'Services');
insert into departments (department_id, department_name) values (212, 'Human Resources');
insert into departments (department_id, department_name) values (213, 'Engineering');
insert into departments (department_id, department_name) values (214, 'Support');
insert into departments (department_id, department_name) values (215, 'Legal');
insert into departments (department_id, department_name) values (216, 'Support');
insert into departments (department_id, department_name) values (217, 'Training');
insert into departments (department_id, department_name) values (218, 'Accounting');
insert into departments (department_id, department_name) values (219, 'Accounting');
insert into departments (department_id, department_name) values (220, 'Sales');
insert into departments (department_id, department_name) values (221, 'Product Management');
insert into departments (department_id, department_name) values (222, 'Legal');
insert into departments (department_id, department_name) values (223, 'Human Resources');
insert into departments (department_id, department_name) values (224, 'Engineering');
insert into departments (department_id, department_name) values (225, 'Legal');
insert into departments (department_id, department_name) values (226, 'Training');
insert into departments (department_id, department_name) values (227, 'Support');
insert into departments (department_id, department_name) values (228, 'Legal');
insert into departments (department_id, department_name) values (229, 'Marketing');
insert into departments (department_id, department_name) values (230, 'Legal');
insert into departments (department_id, department_name) values (231, 'Engineering');
insert into departments (department_id, department_name) values (232, 'Support');
insert into departments (department_id, department_name) values (233, 'Marketing');
insert into departments (department_id, department_name) values (234, 'Support');
insert into departments (department_id, department_name) values (235, 'Support');
insert into departments (department_id, department_name) values (236, 'Services');
insert into departments (department_id, department_name) values (237, 'Sales');
insert into departments (department_id, department_name) values (238, 'Services');
insert into departments (department_id, department_name) values (239, 'Legal');
insert into departments (department_id, department_name) values (240, 'Training');
insert into departments (department_id, department_name) values (241, 'Training');
insert into departments (department_id, department_name) values (242, 'Training');
insert into departments (department_id, department_name) values (243, 'Services');
insert into departments (department_id, department_name) values (244, 'Research and Development');
insert into departments (department_id, department_name) values (245, 'Accounting');
insert into departments (department_id, department_name) values (246, 'Research and Development');
insert into departments (department_id, department_name) values (247, 'Engineering');
insert into departments (department_id, department_name) values (248, 'Legal');
insert into departments (department_id, department_name) values (249, 'Business Development');
insert into departments (department_id, department_name) values (250, 'Research and Development');
insert into departments (department_id, department_name) values (251, 'Research and Development');
insert into departments (department_id, department_name) values (252, 'Sales');
insert into departments (department_id, department_name) values (253, 'Support');
insert into departments (department_id, department_name) values (254, 'Training');
insert into departments (department_id, department_name) values (255, 'Accounting');
insert into departments (department_id, department_name) values (256, 'Legal');
insert into departments (department_id, department_name) values (257, 'Marketing');
insert into departments (department_id, department_name) values (258, 'Marketing');
insert into departments (department_id, department_name) values (259, 'Sales');
insert into departments (department_id, department_name) values (260, 'Support');
insert into departments (department_id, department_name) values (261, 'Human Resources');
insert into departments (department_id, department_name) values (262, 'Marketing');
insert into departments (department_id, department_name) values (263, 'Marketing');
insert into departments (department_id, department_name) values (264, 'Support');
insert into departments (department_id, department_name) values (265, 'Services');
insert into departments (department_id, department_name) values (266, 'Product Management');
insert into departments (department_id, department_name) values (267, 'Business Development');
insert into departments (department_id, department_name) values (268, 'Marketing');
insert into departments (department_id, department_name) values (269, 'Engineering');
insert into departments (department_id, department_name) values (270, 'Accounting');
insert into departments (department_id, department_name) values (271, 'Services');
insert into departments (department_id, department_name) values (272, 'Product Management');
insert into departments (department_id, department_name) values (273, 'Accounting');
insert into departments (department_id, department_name) values (274, 'Research and Development');
insert into departments (department_id, department_name) values (275, 'Engineering');
insert into departments (department_id, department_name) values (276, 'Engineering');
insert into departments (department_id, department_name) values (277, 'Training');
insert into departments (department_id, department_name) values (278, 'Support');
insert into departments (department_id, department_name) values (279, 'Engineering');
insert into departments (department_id, department_name) values (280, 'Sales');
insert into departments (department_id, department_name) values (281, 'Services');
insert into departments (department_id, department_name) values (282, 'Sales');
insert into departments (department_id, department_name) values (283, 'Human Resources');
insert into departments (department_id, department_name) values (284, 'Marketing');
insert into departments (department_id, department_name) values (285, 'Business Development');
insert into departments (department_id, department_name) values (286, 'Legal');
insert into departments (department_id, department_name) values (287, 'Human Resources');
insert into departments (department_id, department_name) values (288, 'Engineering');
insert into departments (department_id, department_name) values (289, 'Engineering');
insert into departments (department_id, department_name) values (290, 'Research and Development');
insert into departments (department_id, department_name) values (291, 'Sales');
insert into departments (department_id, department_name) values (292, 'Human Resources');
insert into departments (department_id, department_name) values (293, 'Marketing');
insert into departments (department_id, department_name) values (294, 'Marketing');
insert into departments (department_id, department_name) values (295, 'Research and Development');
insert into departments (department_id, department_name) values (296, 'Business Development');
insert into departments (department_id, department_name) values (297, 'Business Development');
insert into departments (department_id, department_name) values (298, 'Training');
insert into departments (department_id, department_name) values (299, 'Marketing');
insert into departments (department_id, department_name) values (300, 'Sales');
insert into departments (department_id, department_name) values (301, 'Research and Development');
insert into departments (department_id, department_name) values (302, 'Support');
insert into departments (department_id, department_name) values (303, 'Research and Development');
insert into departments (department_id, department_name) values (304, 'Research and Development');
insert into departments (department_id, department_name) values (305, 'Research and Development');
insert into departments (department_id, department_name) values (306, 'Business Development');
insert into departments (department_id, department_name) values (307, 'Sales');
insert into departments (department_id, department_name) values (308, 'Human Resources');
insert into departments (department_id, department_name) values (309, 'Engineering');
insert into departments (department_id, department_name) values (310, 'Research and Development');
insert into departments (department_id, department_name) values (311, 'Support');
insert into departments (department_id, department_name) values (312, 'Legal');
insert into departments (department_id, department_name) values (313, 'Product Management');
insert into departments (department_id, department_name) values (314, 'Engineering');
insert into departments (department_id, department_name) values (315, 'Services');
insert into departments (department_id, department_name) values (316, 'Business Development');
insert into departments (department_id, department_name) values (317, 'Services');
insert into departments (department_id, department_name) values (318, 'Services');
insert into departments (department_id, department_name) values (319, 'Legal');
insert into departments (department_id, department_name) values (320, 'Training');
insert into departments (department_id, department_name) values (321, 'Engineering');
insert into departments (department_id, department_name) values (322, 'Engineering');
insert into departments (department_id, department_name) values (323, 'Marketing');
insert into departments (department_id, department_name) values (324, 'Legal');
insert into departments (department_id, department_name) values (325, 'Research and Development');
insert into departments (department_id, department_name) values (326, 'Human Resources');
insert into departments (department_id, department_name) values (327, 'Marketing');
insert into departments (department_id, department_name) values (328, 'Accounting');
insert into departments (department_id, department_name) values (329, 'Support');
insert into departments (department_id, department_name) values (330, 'Support');
insert into departments (department_id, department_name) values (331, 'Research and Development');
insert into departments (department_id, department_name) values (332, 'Sales');
insert into departments (department_id, department_name) values (333, 'Legal');
insert into departments (department_id, department_name) values (334, 'Accounting');
insert into departments (department_id, department_name) values (335, 'Legal');
insert into departments (department_id, department_name) values (336, 'Support');
insert into departments (department_id, department_name) values (337, 'Product Management');
insert into departments (department_id, department_name) values (338, 'Training');
insert into departments (department_id, department_name) values (339, 'Human Resources');
insert into departments (department_id, department_name) values (340, 'Human Resources');
insert into departments (department_id, department_name) values (341, 'Research and Development');
insert into departments (department_id, department_name) values (342, 'Human Resources');
insert into departments (department_id, department_name) values (343, 'Business Development');
insert into departments (department_id, department_name) values (344, 'Research and Development');
insert into departments (department_id, department_name) values (345, 'Training');
insert into departments (department_id, department_name) values (346, 'Human Resources');
insert into departments (department_id, department_name) values (347, 'Human Resources');
insert into departments (department_id, department_name) values (348, 'Services');
insert into departments (department_id, department_name) values (349, 'Human Resources');
insert into departments (department_id, department_name) values (350, 'Research and Development');
insert into departments (department_id, department_name) values (351, 'Accounting');
insert into departments (department_id, department_name) values (352, 'Training');
insert into departments (department_id, department_name) values (353, 'Sales');
insert into departments (department_id, department_name) values (354, 'Human Resources');
insert into departments (department_id, department_name) values (355, 'Support');
insert into departments (department_id, department_name) values (356, 'Legal');
insert into departments (department_id, department_name) values (357, 'Product Management');
insert into departments (department_id, department_name) values (358, 'Business Development');
insert into departments (department_id, department_name) values (359, 'Research and Development');
insert into departments (department_id, department_name) values (360, 'Engineering');
insert into departments (department_id, department_name) values (361, 'Support');
insert into departments (department_id, department_name) values (362, 'Accounting');
insert into departments (department_id, department_name) values (363, 'Research and Development');
insert into departments (department_id, department_name) values (364, 'Support');
insert into departments (department_id, department_name) values (365, 'Human Resources');
insert into departments (department_id, department_name) values (366, 'Research and Development');
insert into departments (department_id, department_name) values (367, 'Support');
insert into departments (department_id, department_name) values (368, 'Research and Development');
insert into departments (department_id, department_name) values (369, 'Human Resources');
insert into departments (department_id, department_name) values (370, 'Human Resources');
insert into departments (department_id, department_name) values (371, 'Product Management');
insert into departments (department_id, department_name) values (372, 'Accounting');
insert into departments (department_id, department_name) values (373, 'Legal');
insert into departments (department_id, department_name) values (374, 'Accounting');
insert into departments (department_id, department_name) values (375, 'Services');
insert into departments (department_id, department_name) values (376, 'Sales');
insert into departments (department_id, department_name) values (377, 'Human Resources');
insert into departments (department_id, department_name) values (378, 'Accounting');
insert into departments (department_id, department_name) values (379, 'Services');
insert into departments (department_id, department_name) values (380, 'Accounting');
insert into departments (department_id, department_name) values (381, 'Human Resources');
insert into departments (department_id, department_name) values (382, 'Training');
insert into departments (department_id, department_name) values (383, 'Research and Development');
insert into departments (department_id, department_name) values (384, 'Training');
insert into departments (department_id, department_name) values (385, 'Marketing');
insert into departments (department_id, department_name) values (386, 'Accounting');
insert into departments (department_id, department_name) values (387, 'Accounting');
insert into departments (department_id, department_name) values (388, 'Services');
insert into departments (department_id, department_name) values (389, 'Training');
insert into departments (department_id, department_name) values (390, 'Human Resources');
insert into departments (department_id, department_name) values (391, 'Business Development');
insert into departments (department_id, department_name) values (392, 'Services');
insert into departments (department_id, department_name) values (393, 'Training');
insert into departments (department_id, department_name) values (394, 'Sales');
insert into departments (department_id, department_name) values (395, 'Sales');
insert into departments (department_id, department_name) values (396, 'Human Resources');
insert into departments (department_id, department_name) values (397, 'Support');
insert into departments (department_id, department_name) values (398, 'Marketing');
insert into departments (department_id, department_name) values (399, 'Services');
insert into departments (department_id, department_name) values (400, 'Training');
insert into departments (department_id, department_name) values (401, 'Research and Development');
insert into departments (department_id, department_name) values (402, 'Accounting');
insert into departments (department_id, department_name) values (403, 'Sales');
insert into departments (department_id, department_name) values (404, 'Product Management');
insert into departments (department_id, department_name) values (405, 'Engineering');
insert into departments (department_id, department_name) values (406, 'Support');
insert into departments (department_id, department_name) values (407, 'Training');
insert into departments (department_id, department_name) values (408, 'Legal');
insert into departments (department_id, department_name) values (409, 'Product Management');
insert into departments (department_id, department_name) values (410, 'Sales');
insert into departments (department_id, department_name) values (411, 'Legal');
insert into departments (department_id, department_name) values (412, 'Product Management');
insert into departments (department_id, department_name) values (413, 'Support');
insert into departments (department_id, department_name) values (414, 'Human Resources');
insert into departments (department_id, department_name) values (415, 'Sales');
insert into departments (department_id, department_name) values (416, 'Support');
insert into departments (department_id, department_name) values (417, 'Human Resources');
insert into departments (department_id, department_name) values (418, 'Training');
insert into departments (department_id, department_name) values (419, 'Services');
insert into departments (department_id, department_name) values (420, 'Marketing');
insert into departments (department_id, department_name) values (421, 'Engineering');
insert into departments (department_id, department_name) values (422, 'Human Resources');
insert into departments (department_id, department_name) values (423, 'Marketing');
insert into departments (department_id, department_name) values (424, 'Human Resources');
insert into departments (department_id, department_name) values (425, 'Services');
insert into departments (department_id, department_name) values (426, 'Product Management');
insert into departments (department_id, department_name) values (427, 'Engineering');
insert into departments (department_id, department_name) values (428, 'Human Resources');
insert into departments (department_id, department_name) values (429, 'Product Management');
insert into departments (department_id, department_name) values (430, 'Sales');
insert into departments (department_id, department_name) values (431, 'Support');
insert into departments (department_id, department_name) values (432, 'Sales');
insert into departments (department_id, department_name) values (433, 'Product Management');
insert into departments (department_id, department_name) values (434, 'Marketing');
insert into departments (department_id, department_name) values (435, 'Engineering');
insert into departments (department_id, department_name) values (436, 'Accounting');
insert into departments (department_id, department_name) values (437, 'Legal');
insert into departments (department_id, department_name) values (438, 'Sales');
insert into departments (department_id, department_name) values (439, 'Engineering');
insert into departments (department_id, department_name) values (440, 'Training');
insert into departments (department_id, department_name) values (441, 'Accounting');
insert into departments (department_id, department_name) values (442, 'Research and Development');
insert into departments (department_id, department_name) values (443, 'Human Resources');
insert into departments (department_id, department_name) values (444, 'Human Resources');
insert into departments (department_id, department_name) values (445, 'Product Management');
insert into departments (department_id, department_name) values (446, 'Business Development');
insert into departments (department_id, department_name) values (447, 'Legal');
insert into departments (department_id, department_name) values (448, 'Accounting');
insert into departments (department_id, department_name) values (449, 'Support');
insert into departments (department_id, department_name) values (450, 'Legal');
insert into departments (department_id, department_name) values (451, 'Product Management');
insert into departments (department_id, department_name) values (452, 'Services');
insert into departments (department_id, department_name) values (453, 'Training');
insert into departments (department_id, department_name) values (454, 'Support');
insert into departments (department_id, department_name) values (455, 'Research and Development');
insert into departments (department_id, department_name) values (456, 'Human Resources');
insert into departments (department_id, department_name) values (457, 'Training');
insert into departments (department_id, department_name) values (458, 'Research and Development');
insert into departments (department_id, department_name) values (459, 'Research and Development');
insert into departments (department_id, department_name) values (460, 'Training');
insert into departments (department_id, department_name) values (461, 'Marketing');
insert into departments (department_id, department_name) values (462, 'Accounting');
insert into departments (department_id, department_name) values (463, 'Human Resources');
insert into departments (department_id, department_name) values (464, 'Services');
insert into departments (department_id, department_name) values (465, 'Research and Development');
insert into departments (department_id, department_name) values (466, 'Accounting');
insert into departments (department_id, department_name) values (467, 'Marketing');
insert into departments (department_id, department_name) values (468, 'Engineering');
insert into departments (department_id, department_name) values (469, 'Product Management');
insert into departments (department_id, department_name) values (470, 'Product Management');
insert into departments (department_id, department_name) values (471, 'Training');
insert into departments (department_id, department_name) values (472, 'Product Management');
insert into departments (department_id, department_name) values (473, 'Engineering');
insert into departments (department_id, department_name) values (474, 'Research and Development');
insert into departments (department_id, department_name) values (475, 'Sales');
insert into departments (department_id, department_name) values (476, 'Accounting');
insert into departments (department_id, department_name) values (477, 'Product Management');
insert into departments (department_id, department_name) values (478, 'Sales');
insert into departments (department_id, department_name) values (479, 'Product Management');
insert into departments (department_id, department_name) values (480, 'Research and Development');
insert into departments (department_id, department_name) values (481, 'Accounting');
insert into departments (department_id, department_name) values (482, 'Marketing');
insert into departments (department_id, department_name) values (483, 'Business Development');
insert into departments (department_id, department_name) values (484, 'Support');
insert into departments (department_id, department_name) values (485, 'Sales');
insert into departments (department_id, department_name) values (486, 'Product Management');
insert into departments (department_id, department_name) values (487, 'Business Development');
insert into departments (department_id, department_name) values (488, 'Business Development');
insert into departments (department_id, department_name) values (489, 'Human Resources');
insert into departments (department_id, department_name) values (490, 'Accounting');
insert into departments (department_id, department_name) values (491, 'Training');
insert into departments (department_id, department_name) values (492, 'Accounting');
insert into departments (department_id, department_name) values (493, 'Engineering');
insert into departments (department_id, department_name) values (494, 'Legal');
insert into departments (department_id, department_name) values (495, 'Marketing');
insert into departments (department_id, department_name) values (496, 'Sales');
insert into departments (department_id, department_name) values (497, 'Training');
insert into departments (department_id, department_name) values (498, 'Marketing');
insert into departments (department_id, department_name) values (499, 'Engineering');
insert into departments (department_id, department_name) values (500, 'Product Management');
insert into departments (department_id, department_name) values (501, 'Sales');
insert into departments (department_id, department_name) values (502, 'Marketing');
insert into departments (department_id, department_name) values (503, 'Training');
insert into departments (department_id, department_name) values (504, 'Product Management');
insert into departments (department_id, department_name) values (505, 'Support');
insert into departments (department_id, department_name) values (506, 'Sales');
insert into departments (department_id, department_name) values (507, 'Legal');
insert into departments (department_id, department_name) values (508, 'Product Management');
insert into departments (department_id, department_name) values (509, 'Research and Development');
insert into departments (department_id, department_name) values (510, 'Business Development');
insert into departments (department_id, department_name) values (511, 'Human Resources');
insert into departments (department_id, department_name) values (512, 'Marketing');
insert into departments (department_id, department_name) values (513, 'Human Resources');
insert into departments (department_id, department_name) values (514, 'Marketing');
insert into departments (department_id, department_name) values (515, 'Legal');
insert into departments (department_id, department_name) values (516, 'Support');
insert into departments (department_id, department_name) values (517, 'Services');
insert into departments (department_id, department_name) values (518, 'Sales');
insert into departments (department_id, department_name) values (519, 'Services');
insert into departments (department_id, department_name) values (520, 'Engineering');
insert into departments (department_id, department_name) values (521, 'Sales');
insert into departments (department_id, department_name) values (522, 'Human Resources');
insert into departments (department_id, department_name) values (523, 'Accounting');
insert into departments (department_id, department_name) values (524, 'Training');
insert into departments (department_id, department_name) values (525, 'Marketing');
insert into departments (department_id, department_name) values (526, 'Product Management');
insert into departments (department_id, department_name) values (527, 'Engineering');
insert into departments (department_id, department_name) values (528, 'Training');
insert into departments (department_id, department_name) values (529, 'Training');
insert into departments (department_id, department_name) values (530, 'Research and Development');
insert into departments (department_id, department_name) values (531, 'Accounting');
insert into departments (department_id, department_name) values (532, 'Sales');
insert into departments (department_id, department_name) values (533, 'Business Development');
insert into departments (department_id, department_name) values (534, 'Human Resources');
insert into departments (department_id, department_name) values (535, 'Sales');
insert into departments (department_id, department_name) values (536, 'Human Resources');
insert into departments (department_id, department_name) values (537, 'Sales');
insert into departments (department_id, department_name) values (538, 'Training');
insert into departments (department_id, department_name) values (539, 'Legal');
insert into departments (department_id, department_name) values (540, 'Sales');
insert into departments (department_id, department_name) values (541, 'Human Resources');
insert into departments (department_id, department_name) values (542, 'Accounting');
insert into departments (department_id, department_name) values (543, 'Engineering');
insert into departments (department_id, department_name) values (544, 'Accounting');
insert into departments (department_id, department_name) values (545, 'Product Management');
insert into departments (department_id, department_name) values (546, 'Product Management');
insert into departments (department_id, department_name) values (547, 'Services');
insert into departments (department_id, department_name) values (548, 'Legal');
insert into departments (department_id, department_name) values (549, 'Research and Development');
insert into departments (department_id, department_name) values (550, 'Human Resources');
insert into departments (department_id, department_name) values (551, 'Sales');
insert into departments (department_id, department_name) values (552, 'Services');
insert into departments (department_id, department_name) values (553, 'Legal');
insert into departments (department_id, department_name) values (554, 'Training');
insert into departments (department_id, department_name) values (555, 'Legal');
insert into departments (department_id, department_name) values (556, 'Legal');
insert into departments (department_id, department_name) values (557, 'Business Development');
insert into departments (department_id, department_name) values (558, 'Marketing');
insert into departments (department_id, department_name) values (559, 'Support');
insert into departments (department_id, department_name) values (560, 'Sales');
insert into departments (department_id, department_name) values (561, 'Services');
insert into departments (department_id, department_name) values (562, 'Human Resources');
insert into departments (department_id, department_name) values (563, 'Human Resources');
insert into departments (department_id, department_name) values (564, 'Business Development');
insert into departments (department_id, department_name) values (565, 'Engineering');
insert into departments (department_id, department_name) values (566, 'Product Management');
insert into departments (department_id, department_name) values (567, 'Services');
insert into departments (department_id, department_name) values (568, 'Support');
insert into departments (department_id, department_name) values (569, 'Support');
insert into departments (department_id, department_name) values (570, 'Sales');
insert into departments (department_id, department_name) values (571, 'Engineering');
insert into departments (department_id, department_name) values (572, 'Legal');
insert into departments (department_id, department_name) values (573, 'Human Resources');
insert into departments (department_id, department_name) values (574, 'Training');
insert into departments (department_id, department_name) values (575, 'Support');
insert into departments (department_id, department_name) values (576, 'Marketing');
insert into departments (department_id, department_name) values (577, 'Human Resources');
insert into departments (department_id, department_name) values (578, 'Research and Development');
insert into departments (department_id, department_name) values (579, 'Marketing');
insert into departments (department_id, department_name) values (580, 'Legal');
insert into departments (department_id, department_name) values (581, 'Product Management');
insert into departments (department_id, department_name) values (582, 'Business Development');
insert into departments (department_id, department_name) values (583, 'Engineering');
insert into departments (department_id, department_name) values (584, 'Sales');
insert into departments (department_id, department_name) values (585, 'Training');
insert into departments (department_id, department_name) values (586, 'Marketing');
insert into departments (department_id, department_name) values (587, 'Services');
insert into departments (department_id, department_name) values (588, 'Human Resources');
insert into departments (department_id, department_name) values (589, 'Engineering');
insert into departments (department_id, department_name) values (590, 'Business Development');
insert into departments (department_id, department_name) values (591, 'Training');
insert into departments (department_id, department_name) values (592, 'Services');
insert into departments (department_id, department_name) values (593, 'Business Development');
insert into departments (department_id, department_name) values (594, 'Services');
insert into departments (department_id, department_name) values (595, 'Engineering');
insert into departments (department_id, department_name) values (596, 'Business Development');
insert into departments (department_id, department_name) values (597, 'Legal');
insert into departments (department_id, department_name) values (598, 'Business Development');
insert into departments (department_id, department_name) values (599, 'Legal');
insert into departments (department_id, department_name) values (600, 'Research and Development');
insert into departments (department_id, department_name) values (601, 'Marketing');
insert into departments (department_id, department_name) values (602, 'Training');
insert into departments (department_id, department_name) values (603, 'Human Resources');
insert into departments (department_id, department_name) values (604, 'Sales');
insert into departments (department_id, department_name) values (605, 'Training');
insert into departments (department_id, department_name) values (606, 'Accounting');
insert into departments (department_id, department_name) values (607, 'Services');
insert into departments (department_id, department_name) values (608, 'Services');
insert into departments (department_id, department_name) values (609, 'Engineering');
insert into departments (department_id, department_name) values (610, 'Training');
insert into departments (department_id, department_name) values (611, 'Services');
insert into departments (department_id, department_name) values (612, 'Sales');
insert into departments (department_id, department_name) values (613, 'Services');
insert into departments (department_id, department_name) values (614, 'Business Development');
insert into departments (department_id, department_name) values (615, 'Engineering');
insert into departments (department_id, department_name) values (616, 'Support');
insert into departments (department_id, department_name) values (617, 'Services');
insert into departments (department_id, department_name) values (618, 'Business Development');
insert into departments (department_id, department_name) values (619, 'Accounting');
insert into departments (department_id, department_name) values (620, 'Marketing');
insert into departments (department_id, department_name) values (621, 'Product Management');
insert into departments (department_id, department_name) values (622, 'Legal');
insert into departments (department_id, department_name) values (623, 'Business Development');
insert into departments (department_id, department_name) values (624, 'Product Management');
insert into departments (department_id, department_name) values (625, 'Services');
insert into departments (department_id, department_name) values (626, 'Engineering');
insert into departments (department_id, department_name) values (627, 'Support');
insert into departments (department_id, department_name) values (628, 'Support');
insert into departments (department_id, department_name) values (629, 'Product Management');
insert into departments (department_id, department_name) values (630, 'Research and Development');
insert into departments (department_id, department_name) values (631, 'Support');
insert into departments (department_id, department_name) values (632, 'Sales');
insert into departments (department_id, department_name) values (633, 'Research and Development');
insert into departments (department_id, department_name) values (634, 'Business Development');
insert into departments (department_id, department_name) values (635, 'Accounting');
insert into departments (department_id, department_name) values (636, 'Accounting');
insert into departments (department_id, department_name) values (637, 'Product Management');
insert into departments (department_id, department_name) values (638, 'Support');
insert into departments (department_id, department_name) values (639, 'Support');
insert into departments (department_id, department_name) values (640, 'Accounting');
insert into departments (department_id, department_name) values (641, 'Sales');
insert into departments (department_id, department_name) values (642, 'Business Development');
insert into departments (department_id, department_name) values (643, 'Marketing');
insert into departments (department_id, department_name) values (644, 'Services');
insert into departments (department_id, department_name) values (645, 'Product Management');
insert into departments (department_id, department_name) values (646, 'Training');
insert into departments (department_id, department_name) values (647, 'Services');
insert into departments (department_id, department_name) values (648, 'Human Resources');
insert into departments (department_id, department_name) values (649, 'Business Development');
insert into departments (department_id, department_name) values (650, 'Human Resources');
insert into departments (department_id, department_name) values (651, 'Product Management');
insert into departments (department_id, department_name) values (652, 'Sales');
insert into departments (department_id, department_name) values (653, 'Business Development');
insert into departments (department_id, department_name) values (654, 'Product Management');
insert into departments (department_id, department_name) values (655, 'Sales');
insert into departments (department_id, department_name) values (656, 'Marketing');
insert into departments (department_id, department_name) values (657, 'Marketing');
insert into departments (department_id, department_name) values (658, 'Accounting');
insert into departments (department_id, department_name) values (659, 'Sales');
insert into departments (department_id, department_name) values (660, 'Engineering');
insert into departments (department_id, department_name) values (661, 'Human Resources');
insert into departments (department_id, department_name) values (662, 'Legal');
insert into departments (department_id, department_name) values (663, 'Accounting');
insert into departments (department_id, department_name) values (664, 'Business Development');
insert into departments (department_id, department_name) values (665, 'Services');
insert into departments (department_id, department_name) values (666, 'Support');
insert into departments (department_id, department_name) values (667, 'Engineering');
insert into departments (department_id, department_name) values (668, 'Support');
insert into departments (department_id, department_name) values (669, 'Support');
insert into departments (department_id, department_name) values (670, 'Accounting');
insert into departments (department_id, department_name) values (671, 'Legal');
insert into departments (department_id, department_name) values (672, 'Human Resources');
insert into departments (department_id, department_name) values (673, 'Services');
insert into departments (department_id, department_name) values (674, 'Support');
insert into departments (department_id, department_name) values (675, 'Sales');
insert into departments (department_id, department_name) values (676, 'Services');
insert into departments (department_id, department_name) values (677, 'Engineering');
insert into departments (department_id, department_name) values (678, 'Support');
insert into departments (department_id, department_name) values (679, 'Accounting');
insert into departments (department_id, department_name) values (680, 'Research and Development');
insert into departments (department_id, department_name) values (681, 'Training');
insert into departments (department_id, department_name) values (682, 'Marketing');
insert into departments (department_id, department_name) values (683, 'Marketing');
insert into departments (department_id, department_name) values (684, 'Support');
insert into departments (department_id, department_name) values (685, 'Sales');
insert into departments (department_id, department_name) values (686, 'Sales');
insert into departments (department_id, department_name) values (687, 'Training');
insert into departments (department_id, department_name) values (688, 'Business Development');
insert into departments (department_id, department_name) values (689, 'Research and Development');
insert into departments (department_id, department_name) values (690, 'Training');
insert into departments (department_id, department_name) values (691, 'Legal');
insert into departments (department_id, department_name) values (692, 'Services');
insert into departments (department_id, department_name) values (693, 'Product Management');
insert into departments (department_id, department_name) values (694, 'Human Resources');
insert into departments (department_id, department_name) values (695, 'Accounting');
insert into departments (department_id, department_name) values (696, 'Services');
insert into departments (department_id, department_name) values (697, 'Accounting');
insert into departments (department_id, department_name) values (698, 'Product Management');
insert into departments (department_id, department_name) values (699, 'Engineering');
insert into departments (department_id, department_name) values (700, 'Product Management');
insert into departments (department_id, department_name) values (701, 'Legal');
insert into departments (department_id, department_name) values (702, 'Sales');
insert into departments (department_id, department_name) values (703, 'Sales');
insert into departments (department_id, department_name) values (704, 'Product Management');
insert into departments (department_id, department_name) values (705, 'Engineering');
insert into departments (department_id, department_name) values (706, 'Marketing');
insert into departments (department_id, department_name) values (707, 'Marketing');
insert into departments (department_id, department_name) values (708, 'Accounting');
insert into departments (department_id, department_name) values (709, 'Engineering');
insert into departments (department_id, department_name) values (710, 'Marketing');
insert into departments (department_id, department_name) values (711, 'Human Resources');
insert into departments (department_id, department_name) values (712, 'Training');
insert into departments (department_id, department_name) values (713, 'Business Development');
insert into departments (department_id, department_name) values (714, 'Accounting');
insert into departments (department_id, department_name) values (715, 'Services');
insert into departments (department_id, department_name) values (716, 'Support');
insert into departments (department_id, department_name) values (717, 'Accounting');
insert into departments (department_id, department_name) values (718, 'Accounting');
insert into departments (department_id, department_name) values (719, 'Research and Development');
insert into departments (department_id, department_name) values (720, 'Services');
insert into departments (department_id, department_name) values (721, 'Support');
insert into departments (department_id, department_name) values (722, 'Product Management');
insert into departments (department_id, department_name) values (723, 'Research and Development');
insert into departments (department_id, department_name) values (724, 'Sales');
insert into departments (department_id, department_name) values (725, 'Services');
insert into departments (department_id, department_name) values (726, 'Accounting');
insert into departments (department_id, department_name) values (727, 'Product Management');
insert into departments (department_id, department_name) values (728, 'Training');
insert into departments (department_id, department_name) values (729, 'Marketing');
insert into departments (department_id, department_name) values (730, 'Product Management');
insert into departments (department_id, department_name) values (731, 'Product Management');
insert into departments (department_id, department_name) values (732, 'Support');
insert into departments (department_id, department_name) values (733, 'Services');
insert into departments (department_id, department_name) values (734, 'Product Management');
insert into departments (department_id, department_name) values (735, 'Accounting');
insert into departments (department_id, department_name) values (736, 'Support');
insert into departments (department_id, department_name) values (737, 'Marketing');
insert into departments (department_id, department_name) values (738, 'Research and Development');
insert into departments (department_id, department_name) values (739, 'Services');
insert into departments (department_id, department_name) values (740, 'Accounting');
insert into departments (department_id, department_name) values (741, 'Legal');
insert into departments (department_id, department_name) values (742, 'Accounting');
insert into departments (department_id, department_name) values (743, 'Engineering');
insert into departments (department_id, department_name) values (744, 'Training');
insert into departments (department_id, department_name) values (745, 'Marketing');
insert into departments (department_id, department_name) values (746, 'Services');
insert into departments (department_id, department_name) values (747, 'Research and Development');
insert into departments (department_id, department_name) values (748, 'Training');
insert into departments (department_id, department_name) values (749, 'Support');
insert into departments (department_id, department_name) values (750, 'Business Development');
insert into departments (department_id, department_name) values (751, 'Sales');
insert into departments (department_id, department_name) values (752, 'Product Management');
insert into departments (department_id, department_name) values (753, 'Business Development');
insert into departments (department_id, department_name) values (754, 'Sales');
insert into departments (department_id, department_name) values (755, 'Sales');
insert into departments (department_id, department_name) values (756, 'Training');
insert into departments (department_id, department_name) values (757, 'Marketing');
insert into departments (department_id, department_name) values (758, 'Legal');
insert into departments (department_id, department_name) values (759, 'Legal');
insert into departments (department_id, department_name) values (760, 'Accounting');
insert into departments (department_id, department_name) values (761, 'Training');
insert into departments (department_id, department_name) values (762, 'Human Resources');
insert into departments (department_id, department_name) values (763, 'Research and Development');
insert into departments (department_id, department_name) values (764, 'Legal');
insert into departments (department_id, department_name) values (765, 'Legal');
insert into departments (department_id, department_name) values (766, 'Services');
insert into departments (department_id, department_name) values (767, 'Human Resources');
insert into departments (department_id, department_name) values (768, 'Support');
insert into departments (department_id, department_name) values (769, 'Legal');
insert into departments (department_id, department_name) values (770, 'Human Resources');
insert into departments (department_id, department_name) values (771, 'Accounting');
insert into departments (department_id, department_name) values (772, 'Services');
insert into departments (department_id, department_name) values (773, 'Accounting');
insert into departments (department_id, department_name) values (774, 'Training');
insert into departments (department_id, department_name) values (775, 'Support');
insert into departments (department_id, department_name) values (776, 'Marketing');
insert into departments (department_id, department_name) values (777, 'Accounting');
insert into departments (department_id, department_name) values (778, 'Human Resources');
insert into departments (department_id, department_name) values (779, 'Sales');
insert into departments (department_id, department_name) values (780, 'Business Development');
insert into departments (department_id, department_name) values (781, 'Marketing');
insert into departments (department_id, department_name) values (782, 'Training');
insert into departments (department_id, department_name) values (783, 'Training');
insert into departments (department_id, department_name) values (784, 'Legal');
insert into departments (department_id, department_name) values (785, 'Human Resources');
insert into departments (department_id, department_name) values (786, 'Sales');
insert into departments (department_id, department_name) values (787, 'Sales');
insert into departments (department_id, department_name) values (788, 'Services');
insert into departments (department_id, department_name) values (789, 'Human Resources');
insert into departments (department_id, department_name) values (790, 'Training');
insert into departments (department_id, department_name) values (791, 'Training');
insert into departments (department_id, department_name) values (792, 'Research and Development');
insert into departments (department_id, department_name) values (793, 'Human Resources');
insert into departments (department_id, department_name) values (794, 'Product Management');
insert into departments (department_id, department_name) values (795, 'Legal');
insert into departments (department_id, department_name) values (796, 'Research and Development');
insert into departments (department_id, department_name) values (797, 'Sales');
insert into departments (department_id, department_name) values (798, 'Sales');
insert into departments (department_id, department_name) values (799, 'Sales');
insert into departments (department_id, department_name) values (800, 'Accounting');
insert into departments (department_id, department_name) values (801, 'Human Resources');
insert into departments (department_id, department_name) values (802, 'Training');
insert into departments (department_id, department_name) values (803, 'Sales');
insert into departments (department_id, department_name) values (804, 'Human Resources');
insert into departments (department_id, department_name) values (805, 'Support');
insert into departments (department_id, department_name) values (806, 'Human Resources');
insert into departments (department_id, department_name) values (807, 'Support');
insert into departments (department_id, department_name) values (808, 'Accounting');
insert into departments (department_id, department_name) values (809, 'Legal');
insert into departments (department_id, department_name) values (810, 'Marketing');
insert into departments (department_id, department_name) values (811, 'Legal');
insert into departments (department_id, department_name) values (812, 'Research and Development');
insert into departments (department_id, department_name) values (813, 'Legal');
insert into departments (department_id, department_name) values (814, 'Research and Development');
insert into departments (department_id, department_name) values (815, 'Engineering');
insert into departments (department_id, department_name) values (816, 'Accounting');
insert into departments (department_id, department_name) values (817, 'Engineering');
insert into departments (department_id, department_name) values (818, 'Legal');
insert into departments (department_id, department_name) values (819, 'Product Management');
insert into departments (department_id, department_name) values (820, 'Marketing');
insert into departments (department_id, department_name) values (821, 'Accounting');
insert into departments (department_id, department_name) values (822, 'Engineering');
insert into departments (department_id, department_name) values (823, 'Product Management');
insert into departments (department_id, department_name) values (824, 'Sales');
insert into departments (department_id, department_name) values (825, 'Sales');
insert into departments (department_id, department_name) values (826, 'Product Management');
insert into departments (department_id, department_name) values (827, 'Sales');
insert into departments (department_id, department_name) values (828, 'Sales');
insert into departments (department_id, department_name) values (829, 'Engineering');
insert into departments (department_id, department_name) values (830, 'Research and Development');
insert into departments (department_id, department_name) values (831, 'Training');
insert into departments (department_id, department_name) values (832, 'Human Resources');
insert into departments (department_id, department_name) values (833, 'Business Development');
insert into departments (department_id, department_name) values (834, 'Engineering');
insert into departments (department_id, department_name) values (835, 'Human Resources');
insert into departments (department_id, department_name) values (836, 'Marketing');
insert into departments (department_id, department_name) values (837, 'Sales');
insert into departments (department_id, department_name) values (838, 'Sales');
insert into departments (department_id, department_name) values (839, 'Engineering');
insert into departments (department_id, department_name) values (840, 'Sales');
insert into departments (department_id, department_name) values (841, 'Business Development');
insert into departments (department_id, department_name) values (842, 'Human Resources');
insert into departments (department_id, department_name) values (843, 'Services');
insert into departments (department_id, department_name) values (844, 'Accounting');
insert into departments (department_id, department_name) values (845, 'Human Resources');
insert into departments (department_id, department_name) values (846, 'Product Management');
insert into departments (department_id, department_name) values (847, 'Sales');
insert into departments (department_id, department_name) values (848, 'Research and Development');
insert into departments (department_id, department_name) values (849, 'Services');
insert into departments (department_id, department_name) values (850, 'Research and Development');
insert into departments (department_id, department_name) values (851, 'Legal');
insert into departments (department_id, department_name) values (852, 'Sales');
insert into departments (department_id, department_name) values (853, 'Support');
insert into departments (department_id, department_name) values (854, 'Marketing');
insert into departments (department_id, department_name) values (855, 'Accounting');
insert into departments (department_id, department_name) values (856, 'Marketing');
insert into departments (department_id, department_name) values (857, 'Engineering');
insert into departments (department_id, department_name) values (858, 'Training');
insert into departments (department_id, department_name) values (859, 'Product Management');
insert into departments (department_id, department_name) values (860, 'Engineering');
insert into departments (department_id, department_name) values (861, 'Legal');
insert into departments (department_id, department_name) values (862, 'Legal');
insert into departments (department_id, department_name) values (863, 'Accounting');
insert into departments (department_id, department_name) values (864, 'Support');
insert into departments (department_id, department_name) values (865, 'Accounting');
insert into departments (department_id, department_name) values (866, 'Product Management');
insert into departments (department_id, department_name) values (867, 'Human Resources');
insert into departments (department_id, department_name) values (868, 'Human Resources');
insert into departments (department_id, department_name) values (869, 'Support');
insert into departments (department_id, department_name) values (870, 'Business Development');
insert into departments (department_id, department_name) values (871, 'Legal');
insert into departments (department_id, department_name) values (872, 'Business Development');
insert into departments (department_id, department_name) values (873, 'Legal');
insert into departments (department_id, department_name) values (874, 'Research and Development');
insert into departments (department_id, department_name) values (875, 'Training');
insert into departments (department_id, department_name) values (876, 'Business Development');
insert into departments (department_id, department_name) values (877, 'Services');
insert into departments (department_id, department_name) values (878, 'Training');
insert into departments (department_id, department_name) values (879, 'Engineering');
insert into departments (department_id, department_name) values (880, 'Human Resources');
insert into departments (department_id, department_name) values (881, 'Sales');
insert into departments (department_id, department_name) values (882, 'Legal');
insert into departments (department_id, department_name) values (883, 'Business Development');
insert into departments (department_id, department_name) values (884, 'Marketing');
insert into departments (department_id, department_name) values (885, 'Services');
insert into departments (department_id, department_name) values (886, 'Engineering');
insert into departments (department_id, department_name) values (887, 'Sales');
insert into departments (department_id, department_name) values (888, 'Business Development');
insert into departments (department_id, department_name) values (889, 'Support');
insert into departments (department_id, department_name) values (890, 'Product Management');
insert into departments (department_id, department_name) values (891, 'Accounting');
insert into departments (department_id, department_name) values (892, 'Human Resources');
insert into departments (department_id, department_name) values (893, 'Services');
insert into departments (department_id, department_name) values (894, 'Product Management');
insert into departments (department_id, department_name) values (895, 'Research and Development');
insert into departments (department_id, department_name) values (896, 'Legal');
insert into departments (department_id, department_name) values (897, 'Marketing');
insert into departments (department_id, department_name) values (898, 'Accounting');
insert into departments (department_id, department_name) values (899, 'Business Development');
insert into departments (department_id, department_name) values (900, 'Human Resources');
insert into departments (department_id, department_name) values (901, 'Business Development');
insert into departments (department_id, department_name) values (902, 'Business Development');
insert into departments (department_id, department_name) values (903, 'Legal');
insert into departments (department_id, department_name) values (904, 'Sales');
insert into departments (department_id, department_name) values (905, 'Product Management');
insert into departments (department_id, department_name) values (906, 'Engineering');
insert into departments (department_id, department_name) values (907, 'Support');
insert into departments (department_id, department_name) values (908, 'Services');
insert into departments (department_id, department_name) values (909, 'Business Development');
insert into departments (department_id, department_name) values (910, 'Legal');
insert into departments (department_id, department_name) values (911, 'Support');
insert into departments (department_id, department_name) values (912, 'Sales');
insert into departments (department_id, department_name) values (913, 'Human Resources');
insert into departments (department_id, department_name) values (914, 'Training');
insert into departments (department_id, department_name) values (915, 'Engineering');
insert into departments (department_id, department_name) values (916, 'Marketing');
insert into departments (department_id, department_name) values (917, 'Support');
insert into departments (department_id, department_name) values (918, 'Legal');
insert into departments (department_id, department_name) values (919, 'Accounting');
insert into departments (department_id, department_name) values (920, 'Training');
insert into departments (department_id, department_name) values (921, 'Product Management');
insert into departments (department_id, department_name) values (922, 'Legal');
insert into departments (department_id, department_name) values (923, 'Engineering');
insert into departments (department_id, department_name) values (924, 'Legal');
insert into departments (department_id, department_name) values (925, 'Sales');
insert into departments (department_id, department_name) values (926, 'Research and Development');
insert into departments (department_id, department_name) values (927, 'Marketing');
insert into departments (department_id, department_name) values (928, 'Research and Development');
insert into departments (department_id, department_name) values (929, 'Human Resources');
insert into departments (department_id, department_name) values (930, 'Human Resources');
insert into departments (department_id, department_name) values (931, 'Support');
insert into departments (department_id, department_name) values (932, 'Sales');
insert into departments (department_id, department_name) values (933, 'Marketing');
insert into departments (department_id, department_name) values (934, 'Marketing');
insert into departments (department_id, department_name) values (935, 'Business Development');
insert into departments (department_id, department_name) values (936, 'Marketing');
insert into departments (department_id, department_name) values (937, 'Support');
insert into departments (department_id, department_name) values (938, 'Product Management');
insert into departments (department_id, department_name) values (939, 'Sales');
insert into departments (department_id, department_name) values (940, 'Legal');
insert into departments (department_id, department_name) values (941, 'Human Resources');
insert into departments (department_id, department_name) values (942, 'Research and Development');
insert into departments (department_id, department_name) values (943, 'Training');
insert into departments (department_id, department_name) values (944, 'Business Development');
insert into departments (department_id, department_name) values (945, 'Business Development');
insert into departments (department_id, department_name) values (946, 'Human Resources');
insert into departments (department_id, department_name) values (947, 'Product Management');
insert into departments (department_id, department_name) values (948, 'Business Development');
insert into departments (department_id, department_name) values (949, 'Training');
insert into departments (department_id, department_name) values (950, 'Training');
insert into departments (department_id, department_name) values (951, 'Engineering');
insert into departments (department_id, department_name) values (952, 'Legal');
insert into departments (department_id, department_name) values (953, 'Research and Development');
insert into departments (department_id, department_name) values (954, 'Legal');
insert into departments (department_id, department_name) values (955, 'Support');
insert into departments (department_id, department_name) values (956, 'Training');
insert into departments (department_id, department_name) values (957, 'Training');
insert into departments (department_id, department_name) values (958, 'Research and Development');
insert into departments (department_id, department_name) values (959, 'Legal');
insert into departments (department_id, department_name) values (960, 'Engineering');
insert into departments (department_id, department_name) values (961, 'Business Development');
insert into departments (department_id, department_name) values (962, 'Human Resources');
insert into departments (department_id, department_name) values (963, 'Legal');
insert into departments (department_id, department_name) values (964, 'Marketing');
insert into departments (department_id, department_name) values (965, 'Product Management');
insert into departments (department_id, department_name) values (966, 'Services');
insert into departments (department_id, department_name) values (967, 'Support');
insert into departments (department_id, department_name) values (968, 'Accounting');
insert into departments (department_id, department_name) values (969, 'Human Resources');
insert into departments (department_id, department_name) values (970, 'Product Management');
insert into departments (department_id, department_name) values (971, 'Support');
insert into departments (department_id, department_name) values (972, 'Research and Development');
insert into departments (department_id, department_name) values (973, 'Sales');
insert into departments (department_id, department_name) values (974, 'Research and Development');
insert into departments (department_id, department_name) values (975, 'Engineering');
insert into departments (department_id, department_name) values (976, 'Services');
insert into departments (department_id, department_name) values (977, 'Services');
insert into departments (department_id, department_name) values (978, 'Sales');
insert into departments (department_id, department_name) values (979, 'Business Development');
insert into departments (department_id, department_name) values (980, 'Human Resources');
insert into departments (department_id, department_name) values (981, 'Accounting');
insert into departments (department_id, department_name) values (982, 'Legal');
insert into departments (department_id, department_name) values (983, 'Research and Development');
insert into departments (department_id, department_name) values (984, 'Sales');
insert into departments (department_id, department_name) values (985, 'Engineering');
insert into departments (department_id, department_name) values (986, 'Human Resources');
insert into departments (department_id, department_name) values (987, 'Human Resources');
insert into departments (department_id, department_name) values (988, 'Accounting');
insert into departments (department_id, department_name) values (989, 'Legal');
insert into departments (department_id, department_name) values (990, 'Support');
insert into departments (department_id, department_name) values (991, 'Sales');
insert into departments (department_id, department_name) values (992, 'Legal');
insert into departments (department_id, department_name) values (993, 'Training');
insert into departments (department_id, department_name) values (994, 'Marketing');
insert into departments (department_id, department_name) values (995, 'Training');
insert into departments (department_id, department_name) values (996, 'Support');
insert into departments (department_id, department_name) values (997, 'Marketing');
insert into departments (department_id, department_name) values (998, 'Support');
insert into departments (department_id, department_name) values (999, 'Research and Development');
insert into departments (department_id, department_name) values (1000, 'Training');
